### ISSUE TITLE
Missing Helm chart for `1.22.0`

### ISSUE THREAD

**Issue by stevehipwell** [aws/aws-node-termination-handler#1003]
**Describe the bug**
Due to the (Windows) build failing the Helm chart hasn't been published.

The Windows build failing is due to it attempting to run a bash script without an interpreter. The call to `upload-resources-to-github` could be temporarily removed from the makefile for Windows to stop this blocking each release. There are a number of potential options for resolving this, I've listed a couple of them out here.

- Write `upload-resources-to-github.ps1` as a PowerShell version of `upload-resources-to-github` to be used for Windows
- Install WSL on the runner and try to use the existing script
- Output the binary from the Windows job and upload in the next job
- Create the binaries with GoReleaser in a separate job to the OCI image creation to create the release and upload the binaries

**Steps to reproduce**
`helm pull oci://public.ecr.aws/aws-ec2/helm/aws-node-termination-handler --version 0.24.0`

**Expected outcome**
I'd expect the Helm chart to have been published.

**Application Logs**
n/a

**Environment**

* NTH App Version:
* NTH Mode (IMDS/Queue processor): 
* OS/Arch:
* Kubernetes version: 
* Installation method:

**Comment by stevehipwell** [comment]
CC @LikithaVemulapalli

**Comment by LikithaVemulapalli** [comment]
Hello @stevehipwell, we are aware of this issue, we will fix this as soon as possible, thank you

**Comment by stevehipwell** [comment]
@LikithaVemulapalli by reverting the `v1.22.0` release you've broken our clusters where we manually set the image tag in the Helm chart, this release was an urgent bug fix. Release artifacts should be immutable, the `v1.22.0` release should have been completed manually so as to not break any usage.

Do you need any help getting the automation working so we can get access to `v1.22.0`.

**Comment by stevehipwell** [comment]
@LikithaVemulapalli why not disable the Windows binary upload for now (skip the script in make), that way you only have to do that one step manually (and if it's missed it's unlikely to be an issue).

**Comment by LikithaVemulapalli** [comment]
yes @stevehipwell , I'm planning to modify the `release-windows` in make file and remove upload-assets-to-windows for now, and add it manually after the release, I wanted to fix this sooner so had the setup ready in my fork to test release, but since the release is urgent, I will do the release, we will have the helm chart uploaded today, thank you.

**Comment by stevehipwell** [comment]
Thanks @LikithaVemulapalli, this is working correctly now.
