### ISSUE TITLE
Support other schedulers like Hashicorp Nomad

### ISSUE THREAD

**Issue by daktari** [aws/aws-node-termination-handler#102]
It would be great that this service supports other schedulers like Hashicorp Nomad or Mesos.

Something like this:

`/node-termination-handler --type nomad/k8s/mesos...`

BR

**Comment by bwagner5** [comment]
I'm not sure how the scheduler would affect the node-termination-handler. Can you elaborate more?

**Comment by bwagner5** [comment]
ah so I think I understand more now... You'd like for aws-node-termination-handler to call back to the nomad/mesos control planes to do their version of cordon and drain process.

**Comment by daktari** [comment]
Yes! Sorry for the bad description. This probably allows that many different AWS users can collaborate to improve this service. Maybe in other repo?

We are not k8s users and we are thinking about develop a very similar service like this  one to drain our nodes.

BR

**Comment by imuqtadir** [comment]
+1

We could use this for SLURM scheduler.

**Comment by bwagner5** [comment]
I'm curious how far, if any, the current webhook functionality could get you wrt integration with other control planes? The webhook functionality in aws-node-termination-handler is pretty customizable in terms of the headers to pass and the body can be templated. Just wanted to throw out this idea.

**Comment by daktari** [comment]
Yes, webhooks could be useful for many situations but we are thinking about draining a node, check node drainig status (with a blocking query or similar) anf gracefuly leave nomad cluster for example in a spot instance termination situation. With webhooks I have to implement an API that makes those simple draining steps afrer webhook call.

I am talking about make aws-note-termination-handler compatible with multiple type of systems like:

```
1.- K8s/Nomad/SLUMR/Mesos...
2.- Webhooks
3.- Publish event somewhere (sqs, rabbitmq...)
3.- Simple command or script. For "not clustered" nodes. For example "systemctl stop nginx" or ./drain.sh custom script
[....]
```

**Comment by bwagner5** [comment]
@daktari completely understand. The only reason I brought up webhooks is that this feature request would be a significant change to the codebase and was curious if other solutions could be helpful in the near term. 

For example, you could easily implement an arbitrary script execution by starting up a tiny http api and have the webhook hit that API and then execute a script to perform the control plane specific draining logic.

**Comment by jillmon** [comment]
We have reviewed this issue and determined that we want to keep this project focused on Kubernetes. Thank you for your suggestion.
