### ISSUE TITLE
ASG launch lifecycle events showing up as `UnknownInterruption`

### ISSUE THREAD

**Issue by stevehipwell** [aws/aws-node-termination-handler#1024]
**Describe the bug**
All events for the ASG launch lifecycle are categorised as `UnknownInterruption` instead of the expected `ASGLifecycle`.

**Steps to reproduce**
Use the ASG launch functionality with K8s events enabled.

**Expected outcome**
I'd expect to see the events categorised as `ASGLifecycle`.

**Application Logs**
n/a

**Environment**

* NTH App Version: 1.22.0
* NTH Mode (IMDS/Queue processor): Queue processor
* OS/Arch:
* Kubernetes version: 
* Installation method: Helm

**Comment by stevehipwell** [comment]
CC @LikithaVemulapalli

**Comment by stevehipwell** [comment]
/not-stale

CC @LikithaVemulapalli

**Comment by LikithaVemulapalli** [comment]
Hello @stevehipwell, we will further see that this issue is not marked as stale and will give an update on this as soon as possible. Thanks!
