### ISSUE TITLE
OCI helm registry is inacessible

### ISSUE THREAD

**Issue by camaeel** [aws/aws-node-termination-handler#1076]
**Describe the bug**
HTTP 403 when trying to get helm chart

**Steps to reproduce**
```
helm template oci://public.ecr.aws/aws-ec2/helm/aws-node-termination-handler --version 0.24.1 | head -10 
```

**Expected outcome**
Command above produces valid template 

**Application Logs**
N/A

**Environment**

* NTH App Version:
* NTH Mode (IMDS/Queue processor): 
* OS/Arch:
* Kubernetes version: 
* Installation method:

**Comment by LikithaVemulapalli** [comment]
Hello @camaeel, I tried to reproduce your issue but I'm getting a valid template for the latest chart version `0.24.1` uploaded in ecr public repo. Could you please verify again and give an update so that we can close this issue. Thanks!

**Comment by kamil-stc** [comment]
It seems the issue was on my side. I had some credentials for public.ecr.aws and they didn't work. 
Sorry for taking your time.
