### ISSUE TITLE
Aws-node-termination-handler helm chart is  trying to hit /metrics endpoint even after setting enable-prometheus-server as false.

### ISSUE THREAD

**Issue by BIPLAVGHOSAL** [aws/aws-node-termination-handler#1078]
**Describe the bug**
Deployed the  `aws-node-termination-handler` Helm chart successfully in EKS cluster, with node-termination-arguments as 

```
enable-prometheus-server: false,
prometheus-server-port: 8080,
```

The Helm chart status is deployed and upon checkin the pod logs, found that it is trying to hit the `/metrics` endpoint for Prometheus and this gives 404 logs in the pod level. 

can you please suggest after setting the `enable-prometheus-server` argument as `false` why it is trying to reach for the server endpoint ?

**Steps to reproduce**
- Use the [aws-node-termination-handler](https://github.com/aws/aws-node-termination-handler) helm chart and deploy to EKS cluster. 
- Check the pod logs.

**Expected outcome**
- When the argument `enable-prometheus-server: false,` is set as `false` it should not automatically try to hit `/metrics` endpoint.

**Application Logs**

![image](https://github.com/user-attachments/assets/eb90d865-9ea7-40c9-bb6e-8ff50ab6fb34)

**Environment**

* NTH App Version:
* NTH Mode (IMDS/Queue processor):
* OS/Arch: Linux
* Kubernetes version: 1.29
* Installation method: Helm chart update via Terraform.
* Helm Chart appVersion : v1.22.1

**Comment by tiationg-kho** [comment]
Solved in latest release. Please let us know if there is any other issue. Thank you!
