### ISSUE TITLE
Host the charts in a standard helm registry

### ISSUE THREAD

**Issue by ksauzz** [aws/aws-node-termination-handler#1085]
**Describe the feature**

I would like to access helm charts from CI/CD by a anonymous user w/ standard helm commands.

**Is the feature request related to a problem?**

Migrating the helm chart to ECR as OCI registry causes breaking changes for our CI/CD and other automation tools because:

- We have to use the different helm commands for OCI registry. see [docs](https://helm.sh/docs/topics/registries)
- public ECR registry need authentication, not allow anonymous access.

It would be nice to host the charts in standard helm registry as well.

**Describe alternatives you've considered**

A description of any alternative solutions or features you've considered.

- Keep hosting the charts in [eks-charts](https://github.com/aws/eks-charts/tree/master).

**Comment by LikithaVemulapalli** [comment]
Hello @ksauzz, we apologize that you are facing issues and cannot access helm charts anonymously. We cannot host helm-charts in eks-charts as eks-charts is not owned by our team and we had issues in the past co-ordinating with other team, so we had our own ECR repo to handle this efficiently, it's almost more than an year that we migrated from eks-charts to ECR public repo. We apologize but we suggest finding a different route to access helm charts for your workloads. Thanks
