### ISSUE TITLE
List released helm charts from CLI

### ISSUE THREAD

**Issue by ksauzz** [aws/aws-node-termination-handler#1086]
**Describe the bug**

After migrating the helm chart repo to ECR(OCI) repo, we cannot list the released helm charts from CLI.

related to #1085 

**Steps to reproduce**

```
% helm search repo --versions oci://public.ecr.aws/aws-ec2/helm/aws-node-termination-handler
No results found
```

**Expected outcome**

```
% helm search repo --versions eks/aws-node-termination-handler | head -5
NAME                                    CHART VERSION   APP VERSION     DESCRIPTION
eks/aws-node-termination-handler        0.21.0          1.19.0          A Helm chart for the AWS Node Termination Handler.
eks/aws-node-termination-handler        0.20.3          1.18.3          A Helm chart for the AWS Node Termination Handler.
eks/aws-node-termination-handler        0.20.2          1.18.2          A Helm chart for the AWS Node Termination Handler.
eks/aws-node-termination-handler        0.20.1          1.18.1          A Helm chart for the AWS Node Termination Handler.
```

**Application Logs**
The log output when experiencing the issue.

**Environment**

* NTH App Version:
* NTH Mode (IMDS/Queue processor): 
* OS/Arch:
* Kubernetes version: 
* Installation method:

**Comment by LikithaVemulapalli** [comment]
Hello @ksauzz, OCI doesn't have in-built support to list all the helm charts uploaded to ECR. We could see that there is an open [issue](https://github.com/helm/helm/issues/11000) in helm GitHub repo asking to support listing of OCI versions. For now, we could suggest using crane `crane ls public.ecr.aws/aws-ec2/helm/aws-node-termination-handler | sort -V` to list the tags from ECR repo and then pull the chart by providing the required version or by manually pulling from ECR repo. Unfortunately, we cannot use aws cli to fetch the helm charts using describe commands for public ECR repositories.

**Comment by ksauzz** [comment]
Thank you. I prepared the script to list versions using `crane` like `helm search repo`. I hope AWS teams wouldn't set a lower rate limit for these anonymous access. This kind of tool has to issue N+1 requests to OCI repo.

```
% ./list-oci.sh public.ecr.aws/aws-ec2/helm/aws-node-termination-handler
NAME                                                      CHART_VERSION  APP_VERSION  DESCRIPTION
public.ecr.aws/aws-ec2/helm/aws-node-termination-handler  0.24.1         1.22.1       A Helm chart for the AWS Node Termination Handler.
public.ecr.aws/aws-ec2/helm/aws-node-termination-handler  0.24.0         1.22.0       A Helm chart for the AWS Node Termination Handler.
public.ecr.aws/aws-ec2/helm/aws-node-termination-handler  0.23.0         1.21.0       A Helm chart for the AWS Node Termination Handler.
public.ecr.aws/aws-ec2/helm/aws-node-termination-handler  0.22.0         1.20.0       A Helm chart for the AWS Node Termination Handler.
```
