### ISSUE TITLE
pkg/observability/opentelemetry.go does not have unit test

### ISSUE THREAD

**Issue by phuhung273** [aws/aws-node-termination-handler#1088]
**Describe the feature**
`pkg/observability/opentelemetry.go` does not have unit test

**Is the feature request related to a problem?**
Im working on https://github.com/aws/aws-node-termination-handler/pull/1083. This requires some changes in `pkg/observability/opentelemetry.go` but it doesn't have any unit test. Make contributors less confident.

As discussed, better to have a separate PR to `refactor pkg/observability/opentelemetry.go to be testable` before any further change

**Comment by tiationg-kho** [comment]
Solved in latest release. Please let us know if there is any other issue. Thank you!
