### ISSUE TITLE
Release for ASG lifecycle support

### ISSUE THREAD

**Issue by zyberon** [aws/aws-node-termination-handler#1095]
Hey I can see in main how you have added the lifecycle support for the IMDS, but i can not still see a release with that, when will be that available?

**Comment by LikithaVemulapalli** [comment]
Hello @zyberon, we are planning to do a release on Monday, thanks for opening this issue.

**Comment by doryer** [comment]
@LikithaVemulapalli Is the release planned for this week?

**Comment by LikithaVemulapalli** [comment]
yes, you will find new release published today, thanks for your patience :)

**Comment by Lu-David** [comment]
Release is out! As always, if there are any problems please feel free to open a new Issue!
