### ISSUE TITLE
Provide dry-run mode

### ISSUE THREAD

**Issue by hrzbrg** [aws/aws-node-termination-handler#11]
**Is your feature request related to a problem? Please describe.**
I would like to compare `aws-node-termination-handler` with our current approach of listening to the CloudWatch event in terms of timing. 

**Describe the solution you would like**
The application should take a `--dry-run` flag that will disable the actual execution of the draining but still print the log messages. During startup it should log out that the application is running in `dry-run` mode.

Thanks
hrzbrg

**Comment by mattrandallbecker** [comment]
Great suggestion, I think the ability to run the daemonset in effectively debug mode makes sense.

Also for some history we did explore listening to the CloudWatch event as a possible avenue for the handler but it required additional infrastructure setup and some minor additional cost to your AWS account.  We are exploring adding some additional flags and we'll try to address this at the same time.
