### ISSUE TITLE
Ever increasing memory usage.

### ISSUE THREAD

**Issue by chrissng** [aws/aws-node-termination-handler#121]
I deployed v1.3.0 of the node termination handler using the official helm chart. I noticed that the memory usage is ever increasing and eventually it reaches the pod memory limit and is OOMKilled. Is there a memory leak somewhere? 

![Screenshot from 2020-03-17 22-27-31](https://user-images.githubusercontent.com/1767795/76866544-a37e1e00-68a7-11ea-9057-d168337f70c9.png)

Logs does not look anything out of the ordinary:
```
$ kubectl logs -f -n kube-system node-termination-handler-hmbs7
aws-node-termination-handler arguments: 
	dry-run: false,
	node-name: ip-x-x-x-x.ap-southeast-1.compute.internal,
	metadata-url: http://169.254.169.254,
	kubernetes-service-host: 172.20.0.1,
	kubernetes-service-port: 443,
	delete-local-data: true,
	ignore-daemon-sets: true,
	pod-termination-grace-period: -1,
	node-termination-grace-period: 120,
	enable-scheduled-event-draining: false,
	enable-spot-interruption-draining: true,
	metadata-tries: 3,
2020/03/17 14:11:36 Trying to get token from IMDSv2
2020/03/17 14:11:36 Got token from IMDSv2
2020/03/17 14:11:36 Startup Metadata Retrieved: {InstanceID:i-xxxx InstanceType:m5.large PublicHostname: PublicIP: LocalHostname:ip-x-x-x-x.ap-southeast-1.compute.internal LocalIP:10.17.16.6}
2020/03/17 14:11:36 Started watching for drain events
2020/03/17 14:11:36 Kubernetes AWS Node Termination Handler has started successfully!
2020/03/17 14:11:36 Started watching for event cancellations
2020/03/17 14:11:36 Started monitoring for Spot ITN events
```

**Comment by mattrandallbecker** [comment]
Must be, we'll investigate the changes between 1.2.0 and 1.3.0 and try to locate what caused this.

**Comment by chrissng** [comment]
Thanks @mattrandallbecker. I am using v1.2.0 and the memory usage is stable after an hour of running.

**Comment by bwagner5** [comment]
We’ve narrowed down the issue and I’m running a test over night to ensure the memory is under control. We will release a patch version tomorrow.

**Comment by chrissng** [comment]
![Screenshot from 2020-03-19 11-14-36](https://user-images.githubusercontent.com/1767795/77028077-41bed080-69db-11ea-9a4c-cda46d329721.png)

Running on v1.3.1 now. Looks like the memory leak is fixed. Closing this issue. 

Thanks @bwagner5 !

**Comment by leoskyrocker** [comment]
The new release is missing the proper assets btw. Was it uploaded via the upload script?
It doesn't have the `all-resources.yaml` file and so on...
Would be a breaking change if someone programmatically downloads the release..

**Comment by bwagner5** [comment]
@leoskyrocker assets have been uploaded. I missed adding the docker login to the new docker generation scripts (we just switched to manifest uploading this week and rewrote the build and upload scripts).  So the automated release failed and we had to manually upload.  Reran the full scripts this morning and looks like everything is uploaded properly, plus we have arm images :D
