### ISSUE TITLE
Chart Daemonset should tolerate all taints by default

### ISSUE THREAD

**Issue by leoskyrocker** [aws/aws-node-termination-handler#127]
The issue is if a node has a taint, currently the handler will not be run in that node. Then if termination happens, services may not be drained properly. Therefore, it should by default tolerate all taints by adding to the Daemonset?

```
...
tolerations:
- operator: "Exists"
...
```

**Comment by jaypipes** [comment]
@leoskyrocker Hi! I think you're correct. It makes sense that NTH should run on all nodes, IMHO.

**Comment by bwagner5** [comment]
Pulling the latest chart from eks-chart (https://github.com/aws/eks-charts/releases/tag/v0.0.16) will default to tolerate all taints. Thanks for the issue!
