### ISSUE TITLE
Document required IAM Policy

### ISSUE THREAD

**Issue by mhulscher** [aws/aws-node-termination-handler#134]
I cannot seem to find the IAM Permissions that are required by the application in the form of an IAM Policy. Does this already exist?

**Comment by mattrandallbecker** [comment]
Currently aws-node-termination handler does not require any IAM permissions.  As it's loaded onto each node it queries the local EC2 Instance Metadata Service to learn about pending shutdown events then makes calls to the Kubernetes control plane.

**Comment by mhulscher** [comment]
Clear, thank you. I was hoping that perhaps the aws-node-termination-handler also dissasociates nodes from the ASG the moment they are scheduled for termination.

**Comment by cablespaghetti** [comment]
Yes I was just looking at this to migrate over from https://github.com/kube-aws/kube-spot-termination-notice-handler

I think this is the one missing feature for this project. However it has always said that the detachment *may bring a replacement instance up sooner*, so maybe an expert could tell us if there are actual benefits to this.

**Comment by mattrandallbecker** [comment]
re: are there benefits to ASG detachment?

I think the best answer I can give is "it depends".

Given the myriad of configuration options I don't think it's possible to say definitively.  If you are using something like Cluster Autoscaler it should be just a matter of seconds for it to see there are pending pods and attempt to launch a replacement.  There could be corner cases depending on how many of the disrupted pods can land on other nodes with free slots, if you have multiple node group sizes, or if you are using something like an overscaler to have some standby capacity ready to absorb interruptions.

That being said, it is certainly top of mind for us that we need better support for dealing with ASG's, this includes but is not limited to instance detachment, responding to rebalance events, and lifecycle hooks support.  You can see some of our work to date and thought process in this related issue: https://github.com/aws/aws-node-termination-handler/issues/14

**Comment by mhulscher** [comment]
Thank you. Will close the issue.
