### ISSUE TITLE
RBAC question: DaemonSet delete

### ISSUE THREAD

**Issue by coderanger** [aws/aws-node-termination-handler#138]
Your sample deployment manifest includes delete permissions for daemonsets. Is this actually used? It looks like maybe it's only needed for running your test suite, and not for normal usage?

**Comment by mattrandallbecker** [comment]
You may be right that these permissions are overly broad. We'll do some testing to see if we can remove them.

**Comment by coderanger** [comment]
I just went looking for any actual calls to a Delete API in the code and didn't find any, but they might be hiding in a library or similar :)

**Comment by bwagner5** [comment]
We've merged the unneeded permissions removal in this repo, but waiting on https://github.com/aws/eks-charts/pull/114 PR to be merged and an eks-charts release.

**Comment by bwagner5** [comment]
released https://github.com/aws/aws-node-termination-handler/releases/tag/v1.4.0

**Comment by bwagner5** [comment]
released https://github.com/aws/aws-node-termination-handler/releases/tag/v1.4.0
