### ISSUE TITLE
JSON Log Output

### ISSUE THREAD

**Issue by jsenon** [aws/aws-node-termination-handler#142]
Is there any possibilities to implement a JSON flag in order to log with JSON format instead of human readable format?
[zerolog](https://github.com/rs/zerolog) with `zerolog.ConsoleWriter` could be used in order to do that?

Thanks

**Comment by bwagner5** [comment]
I'm not against the idea, but I'm curious what they would be used for. I assume metrics would be derived from the json logs, would a prometheus metric path be a better solution for that?

**Comment by jsenon** [comment]
Prometheus metrics is also a great idea. 
Regarding the logs, many Kubernetes system have now a stack with Fluent - Elastic - Kibana. Because we don't want to add specific filter in order to be able to search element inside Elasticsearch cluster, JSON logs offer the possibility to parse and index the log automatically based on JSON key without modification.

**Comment by bwagner5** [comment]
released https://github.com/aws/aws-node-termination-handler/releases/tag/v1.4.0
