### ISSUE TITLE
Cannot send slack webhook call via proxy

### ISSUE THREAD

**Issue by georambo** [aws/aws-node-termination-handler#144]
We only allow external traffic via an outgoing proxy.  We should be able to pass ENV variables to the daemonset, so we can pass in https_proxy, and slack call should use this value if it is set.  Otherwise, the slack calls are not getting out of the network.

**Comment by bwagner5** [comment]
Sounds like a good thing to add. I'll post back when we're able to implement this. Or if anyone from the community wants to contribute ;)

**Comment by bwagner5** [comment]
released https://github.com/aws/aws-node-termination-handler/releases/tag/v1.4.0
