### ISSUE TITLE
Taint nodes when termination notification is detected

### ISSUE THREAD

**Issue by diversario** [aws/aws-node-termination-handler#160]
Similar to how [`cluster-autoscaler` uses taints when marking nodes for scale down](https://github.com/kubernetes/autoscaler/blob/912d923484b826b6986046405d243f9083ceb764/cluster-autoscaler/utils/deletetaint/delete.go#L35-L36), `aws-node-termination-handler` should taint nodes which will be terminated, _in addition_ to everything it does currently. This issue is slightly similar to #123 but the proposal is to add to the current behavior.

The reason for this is to make it possible to detect programmatically that a spot node becoming unschedulable in k8s is due to termination vs due to cluster issues. For example, when using `prometheus-operator`, default `KubeNodeUnreachable` alert looks like this:

```
kube_node_spec_taint{effect="NoSchedule",job="kube-state-metrics",key="node.kubernetes.io/unreachable"}
```

which often misfires for nodes being scaled down by the cluster-autoscaler. To fix the problem, we can drop nodes with a taint:

```
kube_node_spec_taint{effect="NoSchedule",job="kube-state-metrics",key="node.kubernetes.io/unreachable"} unless on(node) kube_node_spec_taint{effect="NoSchedule",job="kube-state-metrics",key="ToBeDeletedByClusterAutoscaler"}
```

If `aws-node-termination-handler` tainted nodes that taint could be incorporated into the alert as well.

I'm happy to PR this if there are no objections.

**Comment by bwagner5** [comment]
That sounds like a good addition to the project. A PR is certainly welcome! 

We have a [node labeling function](https://github.com/aws/aws-node-termination-handler/blob/b6477836cc81f6c2e82ca9840adf170472bbd0fc/pkg/node/node.go#L194) already defined, so shouldn't be too hard to add a taint function in the node pkg. 

Also, should the taint only be applied to spot interruption termination notices (ITNs) or should it also apply to EC2 scheduled maintenance events? Maybe it would make sense to have an aws-node-termination-handler/spot-itn and aws-node-termination-handler/scheduled-maintenance? 

If we include tainting at this [point](https://github.com/aws/aws-node-termination-handler/blob/b6477836cc81f6c2e82ca9840adf170472bbd0fc/cmd/node-termination-handler.go#L176) in the code, we'll have the information needed to differentiate between a maintenance event and a spot ITN. Alternatively, the taint could be added to each of the drain events [PreDrainTask](https://github.com/aws/aws-node-termination-handler/blob/b6477836cc81f6c2e82ca9840adf170472bbd0fc/pkg/interruptionevent/scheduled-event.go#L82) hooks.
