### ISSUE TITLE
Manifests in the repository

### ISSUE THREAD

**Issue by janludvikd3** [aws/aws-node-termination-handler#168]
Hi,

I apologize if the suggestions is dumb but we have following problem:

We are starting to use ArgoCD as a tool to deploy cluster addons. Node termination handler is one of them. Currently we are not making any changes to it and deploy it as it is in releases. We are using helm for some addons where we add different configuration values but for this addons helm chart seems like unnecessary dependency. Ideally we would specify the manifests directly, maybe as a base in kustomize and overlay something if needed.

The problem is this addon doesn't have manifests in the repository so we cannot refer to them. I haven't found a way to refer to the release package. If there isn't something I missed, would it be possible to publish and tag every new version in the repo?

Thanks!

**Comment by bwagner5** [comment]
Not a dumb suggestion at all! 
We actually have the resource files uploaded as static release assets on each release.

https://github.com/aws/aws-node-termination-handler/releases/tag/v1.4.0

There are two consumable versions:
 - [all-resources.yaml](https://github.com/aws/aws-node-termination-handler/releases/download/v1.4.0/all-resources.yaml) - This file includes all kubernetes yaml docs in one file. This is good if you don't want to make any changes and apply it directly.
 - [individual-resources.tar](https://github.com/aws/aws-node-termination-handler/releases/download/v1.4.0/individual-resources.tar) - This tar file includes the yaml documents in individual files. This can easily be used with kustomize for attribute modifications. 

Hope this helps! Let us know if there is any room for improvement consuming these files (we should probably update docs to tell people this exists 😊 )

**Comment by janludvikd3** [comment]
Thanks for the response!
In the meantime I decided to use helm for node termination handler as well. Partly because there seems to be a bug in kustomize in version bundled with ArgoCD 1.5.5 which blocks downloading of https resources - and that might have been the reason why it didn't work for me in the first place. Might test it later when there is a new kustomize in ArgoCD.
