### ISSUE TITLE
Feature Request: Add lifecycle labels to nodes

### ISSUE THREAD

**Issue by adnankobir** [aws/aws-node-termination-handler#169]
We run ASGs with mixed on-demand and spot instances. Given the nature of spot instances and some of our workloads, we need the ability to use Node Affinity rules to ensure we get a good spread between the on-demand nodes and the spot nodes (or avoid spot instances altogether for certain workloads).

Would it be feasible to have NTH query the metadata API and retrieve the lifecycle of the running node and attach a `lifecycle=spot` or `lifecycle=on-demand` label to the node upon startup?

**Comment by bwagner5** [comment]
Definitely a good feature request! Unfortunately, lifecycle is not available in EC2 metadata and I'm not aware of another way to retrieve the data without credentials to make an API call.  We're open to suggestions though.

**Comment by adnankobir** [comment]
> Definitely a good feature request! Unfortunately, lifecycle is not available in EC2 metadata and I'm not aware of another way to retrieve the data without credentials to make an API call. We're open to suggestions though.

Would you have any issues with making an authenticated API call? If not I'd like to take this on and enable this functionality behind a feature flag.

**Comment by bwagner5** [comment]
I would be hesitant to add an authenticated API call to the NTH daemonset.   If we end up creating a controller version of NTH (https://github.com/aws/aws-node-termination-handler/issues/14), then it would make perfect sense. 

KOPS is currently labeling spot nodes in the kops controller, if you happen to be using kops currently :) . 

If not, I think a really simple controller could be created as a standalone in the meantime for your use-case, but I'd rather keep authenticated calls out of the NTH daemonset for ease of use and setup.

**Comment by adnankobir** [comment]
Thanks for the quick response. Closing the issue and will keep an eye on  https://github.com/aws/aws-node-termination-handler/issues/14 is decided.
