### ISSUE TITLE
Prometheus metric path

### ISSUE THREAD

**Issue by manute** [aws/aws-node-termination-handler#171]
Hi,

Thanks for this project, it's very useful.  

Looking at the documentation I could not find any prometheus path, so Can it be added or do you think is not needed? 

I can work on a PR if that's ok.

[edited: typo]

**Comment by bwagner5** [comment]
I think prometheus metrics could be useful if it's behind a configuration flag. Since NTH is a daemonset, some users may not want to waste the extra overhead of running an http server for metrics if they're not interested in them.  Feel free to work on a PR!

**Comment by manute** [comment]
Hey @bwagner5 , I just created this #172 .

**Comment by bwagner5** [comment]
released in v1.5.0!
