### ISSUE TITLE
aws-node-termination-handler Network I/O issues with pod

### ISSUE THREAD

**Issue by akapshuk** [aws/aws-node-termination-handler#173]
I don't have any way to reproduce this issue, but found it after taking a look at bills. Few days ago something starting eating ~100$/day after investigation - it was a NAT gateway and I found a source of traffic.
![Screenshot_20200616_165934](https://user-images.githubusercontent.com/1126411/84785302-06409c00-aff4-11ea-8172-b08f04d007c7.png)
![Screenshot_20200616_171023](https://user-images.githubusercontent.com/1126411/84785570-4e5fbe80-aff4-11ea-8a2c-18f89f958100.png)
First screen shows overall picture and second - exact timeframe when it started.
Hopefully the form of graph will help to identify an issue.
Here is a part of log. It's full of that: 

> 2020/06/16 11:54:04 Trying to get token from IMDSv2
> 2020/06/16 11:54:04 Got token from IMDSv2
> 2020/06/16 12:53:52 Trying to get token from IMDSv2
> 2020/06/16 12:53:52 Got token from IMDSv2
> 2020/06/16 13:53:40 Trying to get token from IMDSv2
> 2020/06/16 13:53:40 Got token from IMDSv2

Which is actually the same as everywhere else.. And I couldn't find anything from logs. 

After deleting pod - new one scheduled pod has same issue with Network IO
![Screenshot_20200616_185612](https://user-images.githubusercontent.com/1126411/84797963-1318bc00-b003-11ea-9659-2db8a2af3a8d.png)

**Comment by bwagner5** [comment]
AWS Node Termination Handler constantly polls the ec2 instance metadata service which is on the host via a link-local 169.254.169.254 address. Polling that address shouldn't cause any NAT GW costs. I'm not sure where that network I/O is coming from. The logs you posted look like normal operation of NTH.  

Are there any other statements in the logs that may provide more insight?

**Comment by bwagner5** [comment]
I don't see a way to investigate further and this issue has been stale for a while. Feel free to reopen if you have some more information that we can look into.

**Comment by akapshuk** [comment]
> I don't see a way to investigate further and this issue has been stale for a while. Feel free to reopen if you have some more information that we can look into.

Hi! Unfortunately I don't have any logs as instance was terminated. Still if you notice traffic generated by that pod was ~200Mbits/second, which is pretty high even for metadata polling, but traffic went definitely via NAT gateway, for which I was billied pretty much. Also I saw this case only on that period of time on 2 instances and never seen after that in same cluster with same software versions, which makes me think it was EC2 bug itself.

**Comment by bwagner5** [comment]
- Do you have a webhook configured? 
 - Is your Image Pull Policy the default "IfNoPresent"? 
 - Do you have scheduled maintenance event handling enabled? 
 - Was there a spot notification or scheduled maintenance event at the time (if enabled)?
