### ISSUE TITLE
Add support for Instance Refresh for EC2 Auto Scaling

### ISSUE THREAD

**Issue by stevehipwell** [aws/aws-node-termination-handler#181]
Can the _AWS Node Termination Handler_ handle the events triggered by [Instance Refresh for EC2 Auto Scaling](https://aws.amazon.com/blogs/compute/introducing-instance-refresh-for-ec2-auto-scaling/) to provide a seamless worker upgrade path? If not is this something that could be supported?

**Comment by bwagner5** [comment]
It's not possible to add support for Instance Refresh with the current daemonset implementation. We are tracking this issue https://github.com/aws/aws-node-termination-handler/issues/14 to support generic shutdown events by responding to ASG lifecycle hooks and events from EventBridge. But active development is not underway yet.

**Comment by bwagner5** [comment]
Hey everyone! 👋  We have listened to your request to expand the aws-node-termination-handler to include all EC2 instances and not just Spot.  

We have pushed a branch to the repo [queue-processor]( https://github.com/aws/aws-node-termination-handler/tree/queue-processor) that allows aws-node-termination-handler to run as a deployment in your cluster and respond to EventBridge termination events from ASG, EC2, and Spot. 

Check out the new README on that branch and let us know what you think
https://github.com/aws/aws-node-termination-handler/tree/queue-processor

This new functionality is currently in Alpha, but we would love your feedback!

**Comment by philomory** [comment]
@bwagner5 Those links are 404s for me, has that branch been merged at this point?

**Comment by bwagner5** [comment]
@philomory Yes, the queue-processor branched is merged into main now. 

It was first released in https://github.com/aws/aws-node-termination-handler/releases/tag/v1.9.0

I'd recommend using the latest release, https://github.com/aws/aws-node-termination-handler/releases/tag/v1.11.0 to try it out

**Comment by philomory** [comment]
So, should this issue be closed?
