### ISSUE TITLE
Use with managed node groups

### ISSUE THREAD

**Issue by kostas-rs** [aws/aws-node-termination-handler#186]
Hi, 

Since managed node groups were introduced, according to AWS:

> Amazon EKS automatically drains nodes using the Kubernetes API during terminations or updates. Updates respect the pod disruption budgets that you set for your pods.

Does this mean `aws-node-termination-handler` is not required when used in conjunction with managed node groups during maintenance events? Does anyone have some experience around that?

Also with managed node groups backed by spot instances in the horizon it would be good to get some clarity in case there is overlapping functionality.

Thank you

**Comment by bwagner5** [comment]
@kostas-rs EKS managed node groups use ASG lifecycle hooks to drain nodes based on ASG termination events. The health checks that ASG performs take into account EC2 status checks which include EC2 scheduled maintenance events (https://docs.aws.amazon.com/autoscaling/ec2/userguide/healthcheck.html).  If you're using EKS managed node groups, you should not need the aws-node-termination-handler for the managed nodes.

**Comment by kostas-rs** [comment]
Thank you @bwagner5.

**Comment by mtparet** [comment]
>  The health checks that ASG performs take into account EC2 status checks which include EC2 scheduled maintenance events

But what about spot instances ? Does it drain also ec2 instances automatically ?

**Comment by snay2** [comment]
Yes, EKS managed node groups will drain EC2 Spot instances when appropriate. [Per the documentation](https://docs.aws.amazon.com/eks/latest/userguide/managed-node-groups.html#managed-node-group-capacity-types-spot):

> When a replacement Spot node is bootstrapped and in the `Ready` state on Kubernetes, Amazon EKS cordons and drains the Spot node that received the rebalance recommendation.

and 

> If a Spot two-minute interruption notice arrives before the replacement Spot node is in a `Ready` state, Amazon EKS starts draining the Spot node that received the rebalance recommendation.
