### ISSUE TITLE
Can not use --set nodeSelector.xxx=yyy anymore

### ISSUE THREAD

**Issue by danil-smirnov** [aws/aws-node-termination-handler#205]
Hi,

After the last release I can not install the Helm chart anymore with the following command

```
helm upgrade --install aws-node-termination-handler \
  --namespace kube-system \
  --set nodeSelector.role=stateless \
  eks/aws-node-termination-handler
```

The error is
```
Error: template: aws-node-termination-handler/templates/daemonset.linux.yaml:157:26: executing "aws-node-termination-handler/templates/daemonset.linux.yaml" at <8>: wrong type for value; expected string; got map[string]interface {}
```

Zero config is working fine.
```
helm upgrade --install aws-node-termination-handler \
  --namespace kube-system \
  eks/aws-node-termination-handler
```

I'm using EKS 1.16 and Helm 3.2.4.

**Comment by bwagner5** [comment]
Thanks for reporting this issue! We were notified yesterday via https://github.com/aws/aws-node-termination-handler/issues/202 and have a patch in PR https://github.com/aws/aws-node-termination-handler/pull/203 .

As a work around, you are able to set the nodeSelector like this:

```
--set nodeSelector="role: stateless"
```

**Comment by danil-smirnov** [comment]
@bwagner5 Hey it works, thanks for the workaround.

**Comment by bwagner5** [comment]
released fix in eks-charts
