### ISSUE TITLE
How to simulate the interruption situation manually to see what aws-node-termination-handler is doing normally

### ISSUE THREAD

**Issue by kavicse87** [aws/aws-node-termination-handler#208]
Looking for a recommendation before we use it in our higher level environment.

Requirement:

We're using self managed kops k8s clusters across all our environment
We decided to use spotallocation capacity optimized statergy
We need to test aws-node-termination-handler e2e in our lower level environment with 2 nodes 1 per AZ. before we say it's production grade and can be used in across the environments
Recommendation required:

How to simulate the situation manually to interrupt the instance and see the aws-node-termination-handler is capturing the event and drain the nodes and restart the pods to other available nodes.
We did manually restart the instance, cancel the spot request that got created as part of this activity, and terminate the instance manually but we couldn't observe anything in the other node's aws-node-termination-handler logs
Does it capture the workload logs also or only the ec2 metadata as per the logs below. We didn't put any pod on the nodes yet.
Observation:
We see this is captured in the aws-node-termination-handler logs as below.

		2020/07/16 17:31:46 Started watching for interruption events
		2020/07/16 17:31:46 Kubernetes AWS Node Termination Handler has started successfully!
		2020/07/16 17:31:46 Started watching for event cancellations
		2020/07/16 17:31:46 Started monitoring for Spot ITN events
		2020/07/16 18:31:34 Trying to get token from IMDSv2
		2020/07/16 18:31:34 Got token from IMDSv2
		2020/07/16 19:31:22 Trying to get token from IMDSv2
		2020/07/16 19:31:22 Got token from IMDSv2
		2020/07/16 20:31:10 Trying to get token from IMDSv2
		2020/07/16 20:31:10 Got token from IMDSv2
		2020/07/16 21:30:58 Trying to get token from IMDSv2
		2020/07/16 21:30:58 Got token from IMDSv2
		2020/07/16 22:30:46 Trying to get token from IMDSv2
		2020/07/16 22:30:46 Got token from IMDSv2

**Comment by kavicse87** [comment]
It's a blocker that we've as of now. Any advise on this would be highly helpful to move ahead with this.

**Comment by habibali95** [comment]
i have the same issue...

**Comment by bwagner5** [comment]
The aws-node-termination-handler logs will show spot interruption events from the EC2 Instance Metadata Service. It does not currently drain nodes on instance terminations/shutdowns, only spot interruption events and ec2 scheduled maintenance events. Both of these events are sourced from the EC2 Instance Metadata Service.

There are several ways to test the spot interruption handling capabilities of the aws-node-termination-handler: 


### [EC2 Metadata Mock](https://github.com/aws/amazon-ec2-metadata-mock)
1. We have open sourced a tool called the ec2-metadata-mock that simulates spot interruption notices and more by starting a mock webserver that serves data similar to EC2 Instance Metadata Service. The tool is easily deployed to kubernetes w/ a helm chart. https://github.com/aws/amazon-ec2-metadata-mock

   1. The ec2-metadata-mock started out as test server for aws-node-termination-handler's end-to-end tests in this repo. We are currently migrating to use the ec2-metadata-mock for e2e tests in this repo, but you can check out our current e2e tests which are fairly extensive: https://github.com/aws/aws-node-termination-handler/tree/master/test/e2e

### [Spot Fleet](https://aws.amazon.com/blogs/compute/taking-advantage-of-amazon-ec2-spot-instance-interruption-notices/)
2. If you'd like to test with real spot interruption notices, you can use a spot-fleet. This blog post describes how you can adjust the capacity of a persistent spot-fleet to trigger spot interruption notices: https://aws.amazon.com/blogs/compute/taking-advantage-of-amazon-ec2-spot-instance-interruption-notices/

Hope this helps! Let us know if you have more questions!  :)

**Comment by kavicse87** [comment]
Thanks @bwagner5  this is really helpful.. We would require to use a drainer which should drain the nodes gracefully. So that the workloads can be moved to other available nodes.. With respect to kops kubernetes nodes.. Otherwise we have no use of running this termination handler as a daemon set right because we can capture those interruptions through cloud watch as well right..

**Comment by kavicse87** [comment]
@bwagner5  
We red this document about 15 days ago and that says it supports node draining and from there we navigated to this git hub project. But why are you saying this isn't draining the node that too with the latest version v1.16.1.  Please clarify as we've been put lot of time and efforts on this so far. 

https://aws.amazon.com/about-aws/whats-new/2019/11/aws-supports-automated-draining-for-spot-instance-nodes-on-kubernetes

**Comment by bwagner5** [comment]
@kavicse87 sorry for the confusion! aws-node-termination-handler does drain nodes. I meant to say that it only drains nodes from spot interruption events. If you would manually terminate your EC2 instance from the AWS console or CLI, aws-node-termination-handler would not drain the node. But if you're using spot instance in a cluster, and one of your spot instances is interrupted by AWS, then aws-node-termination-handler will drain the node.

**Comment by kavicse87** [comment]
Thanks for the clarification!! With that we'll test out the functionality by simulating the situation.. Let's get back to you with the findings.

**Comment by kavicse87** [comment]
@bwagner5  finally Ive got instance provisioned which is from >20% of interruption and the instances getting terminated because of the spot interruption saying that capacity isn't available to the respective spot request.. I did see nothing in the AWS node termination handler logs with respect to its draining the node or instance gets interrupted like that.. Can you please clarify this?

**Comment by kavicse87** [comment]
@bwagner5 Please advise when you get a chance to look into it..

**Comment by kavicse87** [comment]
@bwagner5 , I see it in the logs but I couldn't see anything in the old kube-apiserver logs, with repect to termination or node draining related information. Please advise.

k logs kube-apiserver-ip-<ips removed> -f -n kube-system | grep aws
I0803 16:04:01.212390       1 trace.go:116] Trace[1684992899]: "Get" url:/api/v1/namespaces/kube-system/pods/aws-node-termination-handler-962sl/log (started: 2020-08-03 16:03:02.56695203 +0000 UTC m=+546897.275706503) (total time: 58.645403352s):
I0803 16:11:04.500192       1 trace.go:116] Trace[795283623]: "Get" url:/api/v1/namespaces/kube-system/pods/aws-node-termination-handler-962sl/log (started: 2020-08-03 16:09:24.141420592 +0000 UTC m=+547278.850175055) (total time: 1m40.358725089s):
I0803 16:32:23.810240       1 trace.go:116] Trace[1753498880]: "Get" url:/api/v1/namespaces/kube-system/pods/aws-node-termination-handler-962sl/log (started: 2020-08-03 16:27:24.234946373 +0000 UTC m=+548358.943700836) (total time: 4m59.575257586s):

**Comment by YakobovLior** [comment]
Hey @bwagner5,
I'm currently facing the same question, we have deployed the daemonset and want to make a test to verify it's behavior alongside the Slack webhook configuration.
I saw the test under this project - https://github.com/aws/aws-node-termination-handler/blob/master/test/e2e/spot-interruption-test
but can you explain more how to use it?
How come the EC2 instances will know that the mock metadata service is the one they should communicate with, and not the real EC2 metadata service?

Thanks,
Lior

**Comment by haugenj** [comment]
@YakobovLior The e2e tests install aws-node-termiation-handler using Helm and set the metadata url [here](https://github.com/aws/aws-node-termination-handler/blob/master/test/e2e/spot-interruption-test#L36). This becomes where aws-node-termination-handler looks for metadata; other applications on the node still look at the real EC2 metadata service. 

We set that environment variable [here](https://github.com/aws/aws-node-termination-handler/blob/master/test/k8s-local-cluster-test/run-test#L18) for the local tests that use a kind cluster, and [here](https://github.com/aws/aws-node-termination-handler/blob/master/test/eks-cluster-test/run-test#L117) for the eks-cluster e2e tests.

Check out the [ReadMe](https://github.com/aws/aws-node-termination-handler/tree/master/test) in our test folder for more info on the e2e tests.

**Comment by haugenj** [comment]
@kavicse87 Hey, sorry for the delay, Brandon's out until next week. Can you clarify what the issue is? Is it that you aren't seeing pods being drained off the nodes when there's an interruption? Or are you still trying to validate this behavior and need more help with simulating an interruption event?

To simulate a Spot interruption event with amazon-ec2-metadata-mock:

Install [amazon-ec2-metadata-mock](https://github.com/aws/amazon-ec2-metadata-mock#installation). Here's one way:
```
kubectl apply -f https://github.com/aws/amazon-ec2-metadata-mock/releases/download/v1.2.0/all-resources.yaml
```

Then change the EC2 metadata service endpoint of aws-node-termnation-handler by Helm installing with the instanceMetadataURL flag like:
```
helm upgrade --install aws-node-termination-handler \
 --set instanceMetadataURL="http://amazon-ec2-metadata-mock-service.default.svc.cluster.local:1338" \
 --namespace kube-system \
 eks/aws-node-termination-handler
```

Then when you check the aws-node-termination-handler logs (`kubectl logs -n kube-system <aws-node-termination-handler-pod>`)you should see a reference to draining, and if you check the nodes they should be marked unschedulable. I'd give you an example log output but my test cluster is broken right now 😔

**Comment by kavicse87** [comment]
@haugenj I'm totally exhausted with chasing up with this thing. Can you help me please ? My nodes are interrupted automatically since they are from >20% interruption, but I couldn't see the draining related output in the node termination handler logs. I'm still stuck, I couldn't justify it does the draining. I don't have to simulate the interruption because I've configured such a way that interruption is occurring.

1. I installed using kubectl apply -f https://github.com/aws/aws-node-termination-handler/releases/download/v1.6.1/all-resources.yaml.

2. Helm installation was saying merge over writer issue for me.. and my environment is running on helm.

Error: 
====
parse error in "aws-node-termination-handler/templates/daemonset.linux.yaml": template: aws-node-termination-handler/templates/daemonset.linux.yaml:28: function "mergeOverwrite" not defined


 3. Does this chart work only with helm 3?



4. The message I've posted below:
   =====================
finally Ive got instance provisioned which is from >20% of interruption and the instances getting terminated because of the spot interruption saying that capacity isn't available from the respective Auto scaling group & spot request in aws console.. I did see nothing in the AWS node termination handler logs with respect to its draining the node or instance gets interrupted like that.. Can you please clarify this?

**Comment by haugenj** [comment]
@kavicse87 I do think our charts are only configured for Helm 3. Can you post the logs from an aws-node-termination-handler pod that was interrupted? Specifically the beginning of the logs that show the config like:
```
aws-node-termination-handler arguments:
	dry-run: false,
	node-name: ip-.us-east-2.compute.internal,
	metadata-url: http://amazon-ec2-metadata-mock-service.default.svc.cluster.local:1338,
	kubernetes-service-host: 10.100.0.1,
	kubernetes-service-port: 443,
	delete-local-data: true,
	ignore-daemon-sets: true,
	pod-termination-grace-period: -1,
	node-termination-grace-period: 120,
	enable-scheduled-event-draining: false,
	enable-spot-interruption-draining: true,
	metadata-tries: 3,
	cordon-only: false,
	taint-node: false,
	json-logging: false,
	webhook-proxy: ,
	uptime-from-file: ,
	enable-prometheus-server: false,
	prometheus-server-port: 9092,
```

Can you also post the exact Spot interruption message you're getting?

**Comment by kavicse87** [comment]
Interruption log as below from the auto scaling group under activity section:
=================================================
Failed | Launching a new EC2 instance. Status Reason: Could not launch Spot Instances. InsufficientInstanceCapacity - There is no Spot capacity available that matches your request. Launching EC2 instance failed. | At 2020-08-07T15:01:58Z an instance was started in response to a difference between desired and actual capacity, increasing the capacity from 0 to 1.

I don't see the corresponding log relevant to node draining in the aws node termination handler:
===============================================================
k logs <aws-node-termination-handler> -n kube-system -f
aws-node-termination-handler arguments:
        dry-run: false,
        node-name: <ip removed>5.<regionname>.compute.internal,
        metadata-url: http://<ipremoved>
        kubernetes-service-host: <service-host>,
        kubernetes-service-port: 443,
        delete-local-data: true,
        ignore-daemon-sets: true,
        pod-termination-grace-period: -1,
        node-termination-grace-period: 120,
        enable-scheduled-event-draining: false,
        enable-spot-interruption-draining: true,
        metadata-tries: 3,
        cordon-only: false,
        taint-node: false,
        json-logging: false,
        webhook-proxy: ,
        uptime-from-file: ,
        enable-prometheus-server: false,
        prometheus-server-port: 9092,
2020/08/07 03:04:39 Trying to get token from IMDSv2
2020/08/07 03:04:39 Got token from IMDSv2
2020/08/07 03:04:39 Startup Metadata Retrieved: {InstanceID:<instanceid> InstanceType:inf1.xlarge PublicHostname: PublicIP: LocalHostname:<ip removed>      5.<Region>.compute.internal LocalIP:<ip removed>}
2020/08/07 03:04:39 Started watching for interruption events
2020/08/07 03:04:39 Kubernetes AWS Node Termination Handler has started successully!
2020/08/07 03:04:39 Started watching for event cancellations
2020/08/07 03:04:39 Started monitoring for Spot ITN events
2020/08/07 04:04:27 Trying to get token from IMDSv2
2020/08/07 04:04:27 Got token from IMDSv2
2020/08/07 05:04:15 Trying to get token from IMDSv2
2020/08/07 05:04:15 Got token from IMDSv2




error: unexpected EOF

**Comment by kavicse87** [comment]
@haugenj any help / advise on this please?

**Comment by haugenj** [comment]
@kavicse87 The "interruption log" you posted looks like a new [instance request](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/troubleshooting-launch.html) failure log, not an actual [interruption](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-interruptions.html) event. There isn't any relation between that error message and an interruption event that triggers the aws-node-termination-handler. 

Using instances with a >20% interruption rate doesn't necessarily mean they'll be interrupted, though it does make it more likely. If you want a consistent test of actual interruption events I suggest following one of the methods that Brandon suggested before.
