### ISSUE TITLE
Error after upgrading from 0.8.0 to 0.9.2

### ISSUE THREAD

**Issue by cjerad** [aws/aws-node-termination-handler#220]
I'm getting the following error since upgrading from 0.8.0 to 0.9.2. Seems potentially related to this PR. I have not set that value.

```
Error: Failed to render chart: exit status 1: Error: template: aws-node-termination-handler/templates/daemonset.linux.yaml:28:85: executing "aws-node-termination-handler/templates/daemonset.linux.yaml" at <.Values.linuxPodAnnotations>: wrong type for value; expected map[string]interface {}; got interface {}
```

_Originally posted by @yurrriq in https://github.com/aws/aws-node-termination-handler/pull/185#issuecomment-668372538_

**Comment by bwagner5** [comment]
eks-charts has been released: https://github.com/aws/eks-charts/releases/tag/v0.0.26
