### ISSUE TITLE
Does this Mitigate AWS ALB Ingress Controller?

### ISSUE THREAD

**Issue by petrukngantuk** [aws/aws-node-termination-handler#225]
Let's say that we have ALB that point to a service in spot instance, and spot instance will be terminated,
Does this tools mitigate / update the ALB Endpoints that pointed to Interrupted spot instance?

**Comment by haugenj** [comment]
There's no unique functionality in aws-node-termination-handler to do this, but if you're using a k8s [Service](https://kubernetes.io/docs/concepts/services-networking/service/) you're good to go. The Service endpoint attached to the load balancer won't change and will automatically update the pod endpoints it forwards to when the pods are evicted and new pods are created. 

This is assuming you're connecting to the pods via the Service and not going to the pods directly.

**Comment by petrukngantuk** [comment]
I see, thanks for the confirmation...
