### ISSUE TITLE
UpdateStrategy Example

### ISSUE THREAD

**Issue by anders-ni** [aws/aws-node-termination-handler#226]
When trying to set an updateStrategy to "RollingUpdate" it appears that the helm template doesn't apply it it properly. 

When I set this in my values:
```
updateStrategy:
  type: RollingUpdate
```

It renders in one line as `updateStrategy:  type: RollingUpdate` which is not valid yaml.

Is there an example of how to properly set the update strategy? Using v1.6.1

![image](https://user-images.githubusercontent.com/52253530/89823297-dce54d80-db16-11ea-8394-f8e5205a1c81.png)

**Comment by pdk27** [comment]
Thanks for reporting the issue. It turns out that the templates were missing the addition of a new line for updateStrategy. 

You can make the changes in the [PR](https://github.com/aws/aws-node-termination-handler/pull/227) to unblock yourself until the changes are released.

**Comment by pdk27** [comment]
The fix is merged in, it should be released soon.

**Comment by bwagner5** [comment]
eks-charts has been released: https://github.com/aws/eks-charts/releases/tag/v0.0.26
