### ISSUE TITLE
support auto scaling ec2 terminated?

### ISSUE THREAD

**Issue by goodboyMa** [aws/aws-node-termination-handler#245]
Hello,
   I am using auto scaling to manage ec2.
   My ec2 instance is on demand. 
   I found The documentation supports spot instances.
   Whether aws-node-termination-handler to support  termination of the instance by Auto Scaling?
Thk

**Comment by bwagner5** [comment]
Hey @goodboyMa !  Currently aws-node-termination-handler does not support termination events from ASG.  We only support spot interruption events and EC2 scheduled maintenance events. 

However, we've been tracking an issue to add this functionality here: https://github.com/aws/aws-node-termination-handler/issues/14
