### ISSUE TITLE
Need to push git tags for at least v1.0.0 bits

### ISSUE THREAD

**Issue by jaypipes** [aws/aws-node-termination-handler#25]
There are no git tags on the aws/aws-node-termination-handler repository, therefore there are no releases listed. However, there is a Docker *image* tag of v1.0.0 in dockerhub. There should be a corresponding git tag of v1.0.0 as well.

Docker image tags should really be derived from the git tag, making the git history the source of truth for all artifact versioning.

I can work on fixing up the Makefile to ensure proper git tags are used for tagging the Docker images.

**Comment by bwagner5** [comment]
I took a crack at this, let me know if this is what you were thinking.

**Comment by bwagner5** [comment]
v1.0.0 released via github and automation completed to automatically push to dockerhub
