### ISSUE TITLE
While trying to upgrade getting error daemon set in inmutable

### ISSUE THREAD

**Issue by tavisca-cchowdhary** [aws/aws-node-termination-handler#263]
`Error: UPGRADE FAILED: cannot patch "node-termination-handler-aws-node-termination-handler" with kind DaemonSet: DaemonSet.apps "node-termination-handler-aws-node-termination-handler" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/instance":"node-termination-handler", "app.kubernetes.io/name":"aws-node-termination-handler", "kubernetes.io/os":"linux"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable`

**Comment by bwagner5** [comment]
Sorry for the delay!  I believe this is because we changed from using the `beta.kubernetes.io/os` key to the regular `kubernetes.io/os` key since the beta ones are deprecated

**Comment by tavisca-cchowdhary** [comment]
@bwagner5 I guess, then to upgrade it we need to uninstall and install it again!
Right?

**Comment by bwagner5** [comment]
Yes, that is correct

**Comment by tavisca-cchowdhary** [comment]
@bwagner5 Thank You.
