### ISSUE TITLE
Add configurable delay to interruption handling

### ISSUE THREAD

**Issue by mattrandallbecker** [aws/aws-node-termination-handler#29]
Currently the daemonset immediately cordons and drains a node upon ITN detection.

We should allow users to define a period to wait before initializing cordon and drain such that they can still perform work in that window.  e.g. if you can successfully cordon and drain in 30 seconds, delay the process 90 seconds.

**Comment by bwagner5** [comment]
functionality to set a configurable node-termination-grace-period has been merged, probably need some better docs

**Comment by bwagner5** [comment]
I'll open a general issue for better docs on configurable values
