### ISSUE TITLE
Add ECR Hosted Image for NTH

### ISSUE THREAD

**Issue by bwagner5** [aws/aws-node-termination-handler#295]
Since dockerhub has begun rate limiting pulls, NTH should offer an ECR hosted image.

**Comment by pahud** [comment]
The support is very important as it's now affecting many CDK users with aws-eks construct.

**Comment by universam1** [comment]
Kind of funny and sad that AWS distributes over docker hub :smile:

**Comment by bwagner5** [comment]
sorry for the delay, you can use this now: https://gallery.ecr.aws/r6b0f9a1/aws-node-termination-handler 

I'll be updating the automation and docs shortly, but the latest v1.11.1 is available there now.

**Comment by bwagner5** [comment]
Windows will be available there after automation is done, so if you need Windows, hang tight.

**Comment by guan840912** [comment]
Hi @bwagner5, about this issue https://github.com/aws/aws-cdk/pull/12141 .
this PR https://github.com/aws/aws-cdk/pull/12141 waiting for `0.13.2` release.
<img width="1104" alt="截圖 2020-12-19 下午1 02 46" src="https://user-images.githubusercontent.com/46012524/102681207-81307c80-41fa-11eb-9d62-24cd57231e8b.png">

**Comment by bwagner5** [comment]
Sorry for the delay on 0.13.2, I've ran into some issues in the release pipeline for windows. I'll get it out as soon as possible.

**Comment by bwagner5** [comment]
Just pushed the v0.13.2 helm chart for NTH which uses the ECR public image by default: https://github.com/aws/eks-charts/releases/tag/v0.0.39
