### ISSUE TITLE
Change namespace used

### ISSUE THREAD

**Issue by MarcusNoble** [aws/aws-node-termination-handler#3]
It'd be good if this didn't use the `default` namespace. 

I had first thought it would be good to just remove the namespace entirely from the YAML manifest (see #2) but it is required for the ClusterRoleBinding so I think it might make more sense to change the namespace to something more appropriate. 
My suggestion would either be default it to `kube-system` or have it create a `aws-node-termination-handler` namespace to use solely for this.

**Comment by nlowe** [comment]
Another vote for `kube-system` here as that's where `aws-node` lives (if you're using it).

**Comment by bwagner5** [comment]
agreed! alb-ingress-controller also lives in kube-system. I'll work on updating. Thanks!

**Comment by bwagner5** [comment]
changed the namespace to kube-system https://github.com/aws/aws-node-termination-handler/commit/77a1e36a243f4a236f1039813a6ddd23b10897eb

**Comment by bwagner5** [comment]
had to revert the commit since the build was failing (seemed to work locally), but I'll take a look at it soon and get that namespace change updated.

**Comment by MarcusNoble** [comment]
@bwagner5 I think the problem is the `ServiceAccount` doesn't have the namespace specified on it so will use whatever is the currently selected namespace while everything else uses `kube-system`.

See here: https://github.com/aws/aws-node-termination-handler/commit/77a1e36a243f4a236f1039813a6ddd23b10897eb#diff-52e4426571ca56bdf1517b4e6aa174fdL37-L42

**Comment by jaypipes** [comment]
Yep, `kube-system` is the appropriate namespace, I think. @MarcusNoble is correct in identifying the source of the failure you're seeing, @bwagner5.

**Comment by coderanger** [comment]
This is an old ticket, but as a heads up it's weird and probably not good to put stuff in kube-system. That's intended to be used for pods created by Kubernetes itself. This should probably go in a namespace named like the software.
