### ISSUE TITLE
Handle instance retirement events

### ISSUE THREAD

**Issue by johanneswuerbach** [aws/aws-node-termination-handler#30]
From time to time AWS is retiring EC2 instances due to underlying hardware or software failures https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/monitoring-instances-status-check_sched.html#types-of-scheduled-events

I would be awesome if the aws-node-termination-handler could watch the instance meta data service to react automatically to those events https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/monitoring-instances-status-check_sched.html#viewing_scheduled_events and drain the affected instance.

Would this be something in scope of this project?

**Comment by mattrandallbecker** [comment]
Yep, definitely within the wheelhouse of this project.  Thanks for the suggestion!

**Comment by mattrandallbecker** [comment]
resolved with 1.2.0 release

https://github.com/aws/aws-node-termination-handler/releases/tag/v1.2.0

keep in mind this feature is off by default for this release but can be enabled via the helm flag outlined in the readme
