### ISSUE TITLE
feature flags for Queue vs IMDS?

### ISSUE THREAD

**Issue by universam1** [aws/aws-node-termination-handler#305]
From the READMEs there is no information which ENVs are enabling or disabling Queue or respectively IMDS.

* It looks like from code that `ENABLE_SQS_TERMINATION_DRAINING`  would enabled Queue Processor!?
* it looks like from code that 
  * `ENABLE_SPOT_INTERRUPTION_DRAINING`
  * `ENABLE_SCHEDULED_EVENT_DRAINING`
  * `ENABLE_REBALANCE_MONITORING`
will enable the IMDS mode!?

**Comment by bwagner5** [comment]
@universam1 that is correct. 

 - ENABLE_SPOT_INTERRUPTION_DRAINING
 - ENABLE_SCHEDULED_EVENT_DRAINING
 - ENABLE_REBALANCE_MONITORING

are only used to turn on or off features of IMDS mode processing. 

Queue Processor Mode can be configured externally by your EventBridge rules, so we only have the one env var `ENABLE_SQS_TERMINATION_DRAINING` 

The environment variables are shown in the respective mode's [Installation and Configuration](https://github.com/aws/aws-node-termination-handler#installation-and-configuration)

**Comment by universam1** [comment]
Thank you for the clearification - this information is good to know!
Would be good to add this to the docs - I cannot spot the ENV variables described anywhere in the link mentioned.
Thank you

**Comment by bwagner5** [comment]
Yeah docs update is probably warranted. It doesn't call them out explicitly, it just shows them used in the helm command examples.

**Comment by brycahta** [comment]
Merged doc updates; closing
