### ISSUE TITLE
hangs: SQS messages not being processed

### ISSUE THREAD

**Issue by universam1** [aws/aws-node-termination-handler#309]
We see with v1.11 at least the issue that it just stops to process further messages. In SQS console it is visible that messages are queing up.
Restarting the pod solves the problem, all messages will be processed.

For some reasons it stops or hangs on something on occasion without a message, no way to resurrect it other than to restart the pod

Is it possible that Golang context with timeouts are not used to mitigate such conditions?

**Comment by haugenj** [comment]
Hey, sorry to hear things aren't working right, sounds like we might have a bug on our hands. 

Can you provide any logs that might help us figure out what's going on? The event loops that processes SQS messages shouldn't ever stop, and afaik there are timeouts on the k8s API calls to prevent them from hanging so I'm not sure what our culprit might be. Perhaps this is related to #307 where the pod goes into a CrashLoopBackOff? 

I'm also curious whether you saw this in v1.09 or v1.10, or if anything changed in your configuration for v1.11? 

---

We're not currently using `context`, how do you see it applying to our case? My (limited) understanding of it is that it's intended more for servers spinning up many goroutines, which I don't think applies in our case. Perhaps if we implemented your suggestion in #310 context would be more applicable? Lmk what I'm missing here

**Comment by universam1** [comment]
Thank you for your response!

I was looking for any logs in this regard but unfortunately not able, which is terrible because I have therefore no information to search and find an instance in this situation.

Only indicator I find is the AWS Console of SQS that reports that a couple of "Messages available" are in the queue, hence they have not been consumed by the NTH. Maybe an idea could be to set up an alert on this message queue length threshold ....

> Perhaps this is related to #307 where the pod goes into a CrashLoopBackOff

Pod is up and running, circumventing this problem for now. BTW no progress there?

> I'm also curious whether you saw this in v1.09 or v1.10

We started using it with v1.11 so unfortunately cannot state anything about earlier versions

> We're not currently using context, how do you see it applying to our case?

Just a Golang suggestion from our experience, that `context.Background` is a trap, it  can easily lead to hanging application since there is no timeout defined with these requests! 
It is simply using `context.WithDeadline` or `context.WithTimeout` that already provides a guarantee not to hang.
Not sure if it is really related to #310 but it could be complementary

**Comment by haugenj** [comment]
Gotcha, if you're able to gather logs please update us here. @brycahta and I walked through the code again to see if we missed anything obvious but we didn't find anything that stood out. 

Could you also post your config? Maybe that would give us some hints. 

If you're not using custom managed ASG tags you could try using version 1.10.0 to see if the same issue arises. And if you're not checking for rebalance recommendations you could go back down to 1.9.0. This would at least help us narrow it down a bit between versions.

**Comment by bwagner5** [comment]
I do agree that there should be a timeout on processing events so we don't get stuck forever on some unforeseen issue, even if we are now concurrently processing events (thanks to @universam1 in #317).  

@universam1 is this happening often enough in your clusters where you'll notice if deploying #317 mitigates it? I still think it's valuable to add the timeout, since if it's happening during serial processing, eventually, those worker go routines could get stuck and cause it to happen again just further in the future.

**Comment by jillmon** [comment]
As follow up on this issue we need to add a timeout for processing events.
