### ISSUE TITLE
Add Functionality to trigger a drain and cordon by creating a custom resource

### ISSUE THREAD

**Issue by dgr237** [aws/aws-node-termination-handler#344]
I am interest in adding functionality to be able to trigger a drain and cordon via the creation of an instance of a custom resource: e.g. Have a CRD: drainrequests.k8s.aws which specifies the name of the node to drain and cordon along with a Grace Period in the spec. On the creation of the Custom Resource the NTH running on the specified node will trigger a drain and cordon (similar to how the SQS Event works). On deletion of the Custom Resource the node will be uncordoned. The status of the CR will be updated to reflect the status of the Drain and Cordon e.g. It will be marked Complete once the node has been successfully drained (or Cancelled if the drain was cancelled).

Please let me know if you would be interested in this feature. I am happy to work on it.

**Comment by bwagner5** [comment]
I'm curious what use-case you'd like to solve for with this feature? It sounds like what you're suggesting would basically be proxying the functionality of the kubernetes eviction API. https://kubernetes.io/docs/tasks/administer-cluster/safely-drain-node/

**Comment by dgr237** [comment]
We have a requirement that all nodes need to be terminated every 2 weeks. I
was looking to develop an operator which could on a schedule drain and
terminate nodes.

We currently have the NTH deployed as a daemonset in the clusters so was
thinking rather than duplicate the draining code have the scheduler create
CRs and then use the NTH Webhook to call back once the drain has completed.
This would then trigger the termination of the EC2.

Hope this explains the logic. Let me know if you have any questions.

**Comment by bwagner5** [comment]
I'm very weary of NTH explicitly terminating nodes by itself. Up to this point, it is only handling the draining of nodes that are being terminated. I'm not sure if NTH should ever have the capability to cause the termination.  

I'm curious if using the ASG "Max Instance Lifetime" feature would accomplish what you're looking to do without having to modify NTH at all. You can set a max lifetime for all instances in your ASG for 2 weeks and then ASG will handling the termination. NTH running in queue-processor mode would then handle the k8s draining part of it. 

Would this work for you? 

https://docs.aws.amazon.com/autoscaling/ec2/userguide/asg-max-instance-lifetime.html

**Comment by dgr237** [comment]
I was not proposing that the NTH would terminate the nodes... I would have a scheduler pod running outside which would resolve when the nodes need to be terminated -  this will not necessarily be based purely on the length of time the instance has been running... eg. It may determine to terminate a node at a 'quiet time'. The idea is this scheduler would create the drain request CR. This would be processed by the NTH. The NTH would once drained would notify the scheduler pod via the webhook. The scheduler would then terminate the node.

**Comment by bwagner5** [comment]
Ok, I see.  Are the nodes running in ASG? If so, NTH in queue-processor mode can be setup to drain based on ASG termination hooks. You could then simplify the interaction with NTH and just call ASG's terminate instance API (https://docs.aws.amazon.com/cli/latest/reference/autoscaling/terminate-instance-in-auto-scaling-group.html).  

Example: 

- Your Scheduler Pod decides to terminate node1
- Scheduler Pod call ASG terminate-instance-in-auto-scaling-group node1
- NTH receives Termination Lifecycle Hook from ASG
- NTH cordon and drains the node
- NTH sends ASG Completes the Lifecycle Hook
- NTH sends webhook however configured
- ASG proceeds to terminate node1

**Comment by dgr237** [comment]
Yes did consider this approach... but probably the final piece in the puzzle is to have the scheduler check if all pods are scheduled before terminating the node and if they are not to wait for the cluster autoscaler to scale up a node and then to terminate the instance in the asg with the 'should-decrement-desired-capacity' set so that the asg is scaled back down.
