### ISSUE TITLE
checkASGTagBeforeDraining ignores instances that don't belong to any ASG

### ISSUE THREAD

**Issue by gabegorelick** [aws/aws-node-termination-handler#347]
When `checkASGTagBeforeDraining` is enabled (the default), NTH's queue processor will ignore events for instances that don't belong to an ASG with the configured tag. However, it also appears [1] to ignore events for instances that don't belong to *any* ASG. 

Obviously, ASG lifecycle event handling isn't relevant if an instance doesn't belong to an ASG. But spot termination event handling is. Furthermore, detaching soon-to-be-terminated spot instances from an ASG is actually a pretty common workflow [2].

Relevant code:
https://github.com/aws/aws-node-termination-handler/blob/e0260bd31fc6267fb04b32a0adf920983c436644/pkg/monitor/sqsevent/sqs-monitor.go#L207-L222

Solution: check the tags on any instance not in an ASG, although then `managedAsgTag` arguably becomes misleading. IMHO, it would be cleaner if NTH only checked *instance* tags (not ASG tags), and renamed the settings to `checkInstanceTagBeforeDraining` and `managedInstanceTag`, but that ship may have sailed. 

[1] I haven't tested this end-to-end on AWS yet, so this is only based on my reading of the code. Apologies in advance if my understanding is incorrect!

[2] Detaching instances isn't supported by NTH (https://github.com/aws/aws-node-termination-handler/issues/141), but it is used by other tools like https://github.com/AutoSpotting/AutoSpotting which can be used in parallel with NTH.

**Comment by bwagner5** [comment]
I'm not opposed to using the instance tag rather than the ASG tag and changing those parameters. It doesn't change too much on the user's side for configuring it since they can just propagate the ASG tag to the instances. 

As far the detach workflow for spot, I think the best approach today is to use ASGs support for ec2 instance rebalance recommendations. EC2 will send a EventBridge event when a capacity rebalance is recommended for your spot instance (before the 2 minute interruption warning), and ASG will automatically launch a new instance to replace it and then terminate the old one. https://docs.aws.amazon.com/autoscaling/ec2/userguide/capacity-rebalance.html

**Comment by gabegorelick** [comment]
> I'm not opposed to using the instance tag rather than the ASG tag and changing those parameters. It doesn't change too much on the user's side for configuring it since they can just propagate the ASG tag to the instances.

Checking instance tags would also enable NTH to only manage a subset of instances in an ASG. I don't have a good use case for this, but it's certainly more general than only checking the ASG tags.

> As far the detach workflow for spot, I think the best approach today is to use ASGs support for ec2 instance rebalance recommendations.

I haven't used AWS's capacity rebalance feature yet, but my understanding is that it can hang indefinitely if no spot instances can be allocated: 

> If the new instances fail to launch or they launch but the health check fails, Amazon EC2 Auto Scaling keeps trying to relaunch them. While it is trying to launch new instances, your old ones will eventually be interrupted and forcibly terminated.

Depending on how worried you are about that, I think there's still potentially a use case for an on-demand ASG that you attach and detach spot instances from (basically how AutoSpotting works). 

Anyway, on-demand instances without ASGs is also possible in Kubernetes (albeit not typically recommended today). See the "Instances without Auto Scaling groups" section of https://aws.amazon.com/blogs/containers/amazon-eks-cluster-multi-zone-auto-scaling-groups/ for example.
