### ISSUE TITLE
Docs claim podTerminationGracePeriod default is 30 but it's actually -1

### ISSUE THREAD

**Issue by gabegorelick** [aws/aws-node-termination-handler#348]
https://github.com/aws/aws-node-termination-handler/tree/e0260bd31fc6267fb04b32a0adf920983c436644/config/helm/aws-node-termination-handler has the following:
![image](https://user-images.githubusercontent.com/610129/104519029-c01ddc00-55c6-11eb-91e3-6a01eb7c968d.png)

But looking at the code, the default is actually -1:
https://github.com/aws/aws-node-termination-handler/blob/d8460d24b2f06b1b7ce6f8f108e8adc9dbd725a0/pkg/config/config.go#L39

I think the confusion stems from the fact that Kubernetes' default is 30, so transitively NTH's default is 30. But if your pod has a custom value, NTH will not override that by default. This could be made clearer in the docs.

**Comment by bwagner5** [comment]
that's a fair point. Maybe changing that column to -1 and then adding a note that kubernetes defaults to 30 seconds? 

Would you care to open a PR for that change too?
