### ISSUE TITLE
Docs incorrectly say deleteLocalData defaults to false

### ISSUE THREAD

**Issue by gabegorelick** [aws/aws-node-termination-handler#349]
Helm documentation says `deleteLocalData` defaults to `false`:
![image](https://user-images.githubusercontent.com/610129/104622514-5c93bd00-565f-11eb-9e27-4a64dacb6ade.png)

But in the code, it looks like it defaults to `true`:
https://github.com/aws/aws-node-termination-handler/blob/d8460d24b2f06b1b7ce6f8f108e8adc9dbd725a0/pkg/config/config.go#L140

Furthermore, https://github.com/aws/aws-node-termination-handler/issues/20#issuecomment-558309920 says the default should be `true`.

**Comment by bwagner5** [comment]
ah yes, you are right the helm docs are incorrect. Would you like to open a PR to change it to true ?

**Comment by gabegorelick** [comment]
@bwagner5 https://github.com/aws/aws-node-termination-handler/pull/350
