### ISSUE TITLE
Move pods to other nodes

### ISSUE THREAD

**Issue by gabegorelick** [aws/aws-node-termination-handler#352]
In Kubernetes, draining a node can get stuck due to pod disruption budgets. When this happens, the only way to resolve it is to "surge" a deployment, i.e. add extra pods on uncordoned nodes. In an ideal world, Kubernetes would do this for you, but it doesn't due to https://github.com/kubernetes/kubernetes/issues/66811. 

Barring Kubernetes implementing this natively, it would be nice if NTH had a solution. A simple implementation could even be to initiate a rolling restart for every deployment with pods on the draining node. A more complicated solution would be to add pods subject to the deployment's `maxSurge` setting (and related deployment update settings).

I recognize that this may be complicated to implement correctly. This is the kind of thing that probably should be implemented by a dedicated library that everything that drains nodes can leverage, but I'm not aware of any existing solutions (but it's very possible I just haven't found them yet!).

**Comment by bwagner5** [comment]
This seems interesting and I think does fall into NTH's wheelhouse. I briefly read the discussion in kubernetes/kubernetes#66811 .  

I think the cordon + rolling restart of the deployment would be do-able as a configuration option.  Although it seems a little intrusive that others pods that are on different nodes also get restarted...

The maxSurge does sound more complicated and a little awkward for NTH to do that.

**Comment by jillmon** [comment]
After reviewing the scope of work required to complete this enhancement, we have decided that the effort is too large for us to prioritize at this time. Thank you for your suggestion, and if this a pain point that continues to hinder your productivity please let us know.
