### ISSUE TITLE
How to handle EC2 termination via console?

### ISSUE THREAD

**Issue by wiseelf** [aws/aws-node-termination-handler#354]
> This project ensures that the Kubernetes control plane responds appropriately to events that can cause your EC2 instance to become unavailable, such as EC2 maintenance events, EC2 Spot interruptions, ASG Scale-In, ASG AZ Rebalance, and EC2 Instance Termination via the API or Console.

Hello! 
I'm trying to setup aws-node-termination-handler in Queue Processor mode. I followed the instruction and aws-node-termination-handler gracefully handles ASG events, spot instances events, but when I shutdown instances via AWS console/API instance is being terminated and aws-node-termination-handler doesn't even send an alert.

What else I need to configure to allow aws-node-termination-handler to gracefully handle such types of events?

**Comment by wiseelf** [comment]
I got the idea and created an additional bridge event for that:
`aws events put-rule --name MyEc2ChangeStateRule --event-pattern "{\"source\": [\"aws.ec2\"],\"detail-type\": [\"EC2 Instance State-change Notification\"]}"`
The question now is how to delay termination of the instance so all pods have time to exit gracefully? Is there any lifehack? :)

**Comment by bwagner5** [comment]
After you created the EventBridge rule, are you getting notified now (assuming you've configured webhooks on NTH)? 
If not, could you post the NTH logs for the time period of your test?

When you terminate an EC2 instance, it should trigger a graceful operating system shutdown which will send a SIGTERM to the kubelet which will in-turn start shutting down pods by propagating that SIGTERM to the containers on the node. If the containers do not shutdown by the kubelet's podTerminationGracePeriod (k8s default is 30s), then it will send a SIGKILL to forcefully terminate the containers.  

As far as the time the init system gives to the kubelet to shutdown before sending the kubelet a SIGKILL may vary depending on how it's installed and configured. But I believe the default for systemd is 90sec. So you could theoretically set the podTerminationGracePeriod to a max of 90sec (probably a bit less than that) to give your pods the best shot of a graceful shutdown.
