### ISSUE TITLE
Queue processor completing ASG lifecycle hook before pods finished terminating

### ISSUE THREAD

**Issue by yzargari** [aws/aws-node-termination-handler#355]
Hello,

I have a use-case for pods that take long time to terminate gracefully (termination grace period of 60s).
When an instance is set to terminate, ASG triggers the hook, cloudwatch event is sent to SNS and NTH captures that event and starts evicting pods. Immediately after, it will go to complete the ASG Lifecycle Hook - causing the instance termination to kick in.

I think NTH should wait to confirm all pods finish evicting before it sends the completion. Thoughts?

**EDIT:** I just realized that NTH has grace period settings that should affect this behavior:
`	pod-termination-grace-period: -1,`
`	node-termination-grace-period: 120,`
Shouldn't pod termination grace period set to negative one make it respect the pods' actual termination grace periods (which as mentioned above are set to 60s)? Is this a bug?

This example is taken from the log when a node was terminated:
```
2021/01/27 08:47:52 ??? Adding new event to the event store event={"Description":"ASG Lifecycle Termination event received. Instance will be interrupted at 2021-01-27 08:47:22 +0000 UTC \n","Drained":false,"EndTime":"0001-01-01T00:00:00Z","EventID":"asg-lifecycle-term-xxxxxxxxxxxxx","InProgress":false,"InstanceID":"i-xxxxxxxxxxxx","Kind":"SQS_TERMINATE","NodeName":"ip-xx-xx-xx-xx.ec2.internal","StartTime":"2021-01-27T08:47:22Z","State":""}
2021/01/27 08:47:52 ??? Cordoning the node
2021/01/27 08:47:52 ??? Draining the node
2021/01/27 08:47:53 ??? WARNING: ignoring DaemonSet-managed Pods: default/xxxxxx, default/xxxxxx, default/xxxxxx, kube-system/xxxxxx, kube-system/xxxxxx, kube-system/xxxxxx, kube-system/xxxxxx, logging/xxxxxx
2021/01/27 08:47:53 ??? evicting pod "xxxxxx-65f8494d9f-tzgst"
2021/01/27 08:47:53 ??? evicting pod "xxxxxx-577f86586c-xkjxg"
2021/01/27 08:47:53 ??? evicting pod "xxxxxx-6f8bbd49cb-rds7t"
2021/01/27 08:47:53 ??? evicting pod "xxxxxx-dd84d86d8-vdz4c"
2021/01/27 08:47:53 ??? evicting pod "xxxxxx-84c5567bb7-zzcl6"
2021/01/27 08:47:53 ??? evicting pod "xxxxxx-6b958c576-5xhqc"
2021/01/27 08:47:53 ??? evicting pod "xxxxxx-75c45dcc85-8bhws"
2021/01/27 08:47:53 ??? evicting pod "xxxxxx-57845b4c54-4rqzw"
2021/01/27 08:47:53 ??? evicting pod "xxxxxx-6c94d7cfd8-xsw2s"
2021/01/27 08:47:53 ??? evicting pod "xxxxxx-0"
2021/01/27 08:47:53 ??? evicting pod "xxxxxx-f69b7d4db-z2r4c"
2021/01/27 08:47:53 ??? evicting pod "xxxxxx-85bb9bffcd-4htt4"
2021/01/27 08:47:53 ??? evicting pod "xxxxxx-7857d77585-44flh"
2021/01/27 08:47:53 ??? evicting pod "xxxxxx-7d4f55bf5c-29hht"
2021/01/27 08:47:53 ??? evicting pod "xxxxxx-6d8cb45499-6h5nf"
2021/01/27 08:47:53 ??? evicting pod "xxxxxx-5d8c859858-qjhg2"
2021/01/27 08:47:53 ??? evicting pod "xxxxxx-57df8ffc5d-w6g6j"
2021/01/27 08:47:53 ??? evicting pod "xxxxxx-65b8cf88f-nsfn7"
2021/01/27 08:47:55 ??? Node successfully cordoned and drained node_name=ip-xx-xx-xx-xx.ec2.internal
2021/01/27 08:47:55 INF Completed ASG Lifecycle Hook (xxxxxx) for instance i-xxxxxxxxxxxx
2021/01/27 08:47:55 ??? SQS Deleted Message: ....
2021/01/27 08:47:55 ??? SQS Deleted Message: ....
2021/01/27 08:49:28 WRN dropping event for an already terminated node error="node: 'i-xxxxxxxxxxxx' in state 'terminated': node metadata unavailable"
2021/01/27 08:51:08 WRN dropping event for an already terminated node error="node: 'i-xxxxxxxxxxxx' in state 'terminated': node metadata unavailable"
```

**Comment by bwagner5** [comment]
hmmm, I've looked through the drain path, and it looks like everything is correct within NTH.  I assume the pods that take a while to shutdown catch the SIGTERM for proper shutdown? 

NTH drain node: https://github.com/aws/aws-node-termination-handler/blob/main/pkg/node/node.go#L108

Drain Helper Struct: https://github.com/kubernetes/kubectl/blob/3ff1afe4e818c989148434ee06713519186bab16/pkg/drain/drain.go#L56

DeleteOrEvict: https://github.com/kubernetes/kubectl/blob/3ff1afe4e818c989148434ee06713519186bab16/pkg/drain/drain.go#L232

Wait for Deletion: https://github.com/kubernetes/kubectl/blob/3ff1afe4e818c989148434ee06713519186bab16/pkg/drain/drain.go#L337

**Comment by yzargari** [comment]
Hi @bwagner5,
Thanks for looking into this. The pods do go into Terminating state, so I assume they catch the SIGTERM.

I don't know if this could be related, but I think most of our pods are running a start script which in turn starts the actual application. I suspect the start script is capturing the SIGTERM and not forwarding it to the child process.
Do you think this could have an impact on NTH? I think not, because the pod do get into terminating state...

**Comment by bwagner5** [comment]
Going into a Terminating state doesn't mean that the pods are catching SIGTERM properly. In order to delay a pod's shutdown, you'll actually want the processes to ignore SIGTERM (or at least see that it's happening and go into a shutdown function). If there isn't special SIGTERM handling, the containers in the pod will just shutdown immediately.  

Alternatively, you might be using a preStop hook which can also delay the actual pod stopping. I think preStop will run before the pod goes into Terminating, so if you're delaying the shutdown w/ preStop, you should notice the pod going into Terminating when the kubelet sends SIGTERM to the pods for shutdown. 

https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination

**Comment by azenk** [comment]
We may be seeing a similar issue.  The pod listed below is catching SIGTERM (using lightship) and outputting the appropriate log messages indicating that the shutdown handler is being processed.  However, the shutdown handler never finishes.

Regardless of the node being terminated, I see a 'Node successfully cordoned and drained' message almost immediately after the last pod logs as evicting.  Interestingly, it *does* wait for eviction errors due to PodDisruptionBudgets.

I've spent a fair amount of time looking at the code and the logs, and I can't see a reasonable explanation for why this should be the case.

For the pod mentioned above that fails to shutdown properly, the NTH logs show the pod as evicted and successfully drained in the same second (~100ms apart according to our logging pipeline). Based on reading the code snippets you linked, it should be polling the API server at 1s intervals waiting for a `get` on all pod objects to return a `not found` error before returning and logging that the node has been drained.

```
2021/02/03 03:04:44 ??? evicting pod "***-69bcc76bf9-x72wh"
2021/02/03 03:04:44 ??? Node successfully cordoned and drained node_name=***.ec2.internal
```

Watching the pod in question using kubectl, I can see it go into terminating state and stay there for 40+ seconds while the node goes from Ready => NotReady => Deleted.  

```
***-69bcc76bf9-x72wh                              0/1     Terminating
```

It's worth noting that the kubectl drain codebase has been updated since the version linked in `go.sum` so the code being used doesn't perfectly match what you've linked above.  However, I didn't see any glaring functional differences.  Maybe I missed something?

**Comment by alanbrent** [comment]
I'm pretty sure we're experiencing the same issue reported here. If I `kubectl drain` a node with the same flags that we're configuring the NTH w/, lifecycle hooks on our Pod containers run correctly. If I tell the ASG to mark a node for termination, the lifecycle hooks start to run, but it appears that the NTH just merrily tells the ASG to finish terminating the node without waiting for the evictions to complete.

<details><summary>NTH logs during termination event</summary>

```
2021/03/12 18:21:33 ??? Adding new event to the event store event={"Description":"ASG Lifecycle Termination event received. Instance will be interrupted at 2021-03-12 18:20:36 +0000 UTC \n","Drained":false,"EndTime":"0001-01-01T00:00:00Z","EventID":"asg-lifecycle-term-61373165326434382d383065382d666138612d393136372d623632666234383239333635","InstanceID":"i-06a0f6e0c04fb8f04","Kind":"SQS_TERMINATE","NodeName":"ip-172-18-93-39.ec2.internal","StartTime":"2021-03-12T18:20:36Z","State":""}
2021/03/12 18:21:33 ??? Cordoning the node
2021/03/12 18:21:33 ??? Successfully added taint on node node_name=ip-172-18-93-39.ec2.internal taint_key=aws-node-termination-handler/asg-lifecycle-termination
2021/03/12 18:21:33 ??? Draining the node
2021/03/12 18:21:33 ??? WARNING: ignoring DaemonSet-managed Pods: default/report-client-sidecar-jrp95, kube-system/aws-node-kf6np, kube-system/kube-proxy-w4tv5, kube-system/tj-registry-5985m, observability-system/fluent-bit-containerlogs-wcp46, observability-system/otelcol-agent-m2x2d
2021/03/12 18:21:33 ??? evicting pod "repo-template-ruby-56d8fbb9df-pgvfc"
2021/03/12 18:21:33 ??? Node successfully cordoned and drained node_name=ip-172-18-93-39.ec2.internal
2021/03/12 18:21:33 ??? Webhook Success: Notification Sent!
2021/03/12 18:21:34 INF Completed ASG Lifecycle Hook (app-workers-zoneb-0-terminate) for instance i-06a0f6e0c04fb8f04
  MD5OfBody: "d71931859d9c1f77582c7ed74d5f6531",
}
2021/03/12 18:21:34 ??? SQS Deleted Message: {
  ReceiptHandle: "AQEBAbDE4w7A8Nx38yOe53GIa0NzaoA3HuMwRfAV4DHQvwJstdWEMuNgblePtIzAksgQjjLSOar3DYxL7tH6nz9tnLA5Uut64vl+mfX//hZ70wk9+WqxQ5w9f8cYuK+g/KEpn/BpGya/wGiyuhaHMA/0uUUm3ntDMpRKQZJZxTriOSF+BjjUsRfQyNDBphnhX9L89tvJ6/a9qSgCbAEykIy0fQqo6CZCIDZat8gBBKarab+j86YVVEYDBoD0J5BLoKgxl0ekVRDjAijM+t44PD5+TvmgC/9wgsp0EWFqzKlb1QNoT1OhKB/oVkVmX4SRt7OcLVusb9O9rJx2IGEkWHnfbga0Xw2rXqVquXmr/caoQ9cdTYzlJCmOFdI+6G+hct1QcGUx0jPoBiRgsDG5WJOO7ZyoPyYI1F/cQTgC0SGKvU4="
  Attributes: {
  Body: "{\"version\":\"0\",\"id\":\"a71e2d48-80e8-fa8a-9167-b62fb4829365\",\"detail-type\":\"EC2 Instance-terminate Lifecycle Action\",\"source\":\"aws.autoscaling\",\"account\":\"266171351246\",\"time\":\"2021-03-12T18:20:36Z\",\"region\":\"us-east-1\",\"resources\":[\"arn:aws:autoscaling:us-east-1:266171351246:autoScalingGroup:b54489bf-3b36-4d7e-a24f-c03fd01ba6c5:autoScalingGroupName/app-workers-zoneb-0\"],\"detail\":{\"LifecycleActionToken\":\"23fa081a-8111-4956-a4f9-56a73ad53192\",\"AutoScalingGroupName\":\"app-workers-zoneb-0\",\"LifecycleHookName\":\"app-workers-zoneb-0-terminate\",\"EC2InstanceId\":\"i-06a0f6e0c04fb8f04\",\"LifecycleTransition\":\"autoscaling:EC2_INSTANCE_TERMINATING\"}}",
    SentTimestamp: "1615573236972"
  },
  MessageId: "c19c73d8-560a-4fb6-9cb2-9c7fd079b183",
```

</details>

This is blocking us from migrating our infra to EKS. How might we get a priority bump on this issue?

**Comment by bwagner5** [comment]
Thanks for posting logs and detailed description @alanbrent ! We will look into this issue more deeply next week and will post back with an update.

**Comment by imuqtadir** [comment]
I took a punt at this and I think I was able to reproduce the bug. 

NTH Logs:
```
2021/03/22 22:19:45 ??? Cordoning the node
2021/03/22 22:19:46 ??? Draining the node
2021/03/22 22:19:46 ??? evicting pod "kube-dns-6c699b5445-wgr8z"
2021/03/22 22:19:46 ??? evicting pod "spark-pi-b0f0c5785c014e94-exec-2"
2021/03/22 22:19:46 ??? evicting pod "spark-pi-driver"
2021/03/22 22:19:46 ??? evicting pod "spark-pi-b0f0c5785c014e94-exec-4"
2021/03/22 22:19:46 ??? Node successfully cordoned and drained node_name=ip-XXX-XX-XX-XXX.ec2.internal
2021/03/22 22:19:46 INF Completed ASG Lifecycle Hook (my-k8s-term-hook) for instance i-XXXXXX
2021/03/22 22:19:46 ??? SQS Deleted Message: {
  Attributes: {
    SentTimestamp: "1616451488543"
  }
```

I had my custom shutdown hook on my driver pod which would wait for 20s to delay the eviction. However, it was abruptly evicted and did not gracefully terminate and ASG lifecycle hook marked complete. Sample logs (matching NTH log timing):
```
21/03/22 22:19:46 WARN ExecutorPodsWatchSnapshotSource: Kubernetes client has been closed (this is expected if the application is shutting down.)
21/03/22 22:19:46 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
21/03/22 22:19:46 INFO MemoryStore: MemoryStore cleared
21/03/22 22:19:46 INFO BlockManager: BlockManager stopped
21/03/22 22:19:46 INFO BlockManagerMaster: BlockManagerMaster stopped
21/03/22 22:19:46 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
21/03/22 22:19:46 INFO SparkContext: Successfully stopped SparkContext
21/03/22 22:19:46 INFO ShutdownHookManager: Shutdown hook called. Now Sleeping 20 seconds..
```
My guess is around the fixes done to [drain.go](https://github.com/kubernetes/kubectl/blob/master/pkg/drain/drain.go) in later releases may fix the issue – particularly this [commit](https://github.com/kubernetes/kubectl/commit/e5ddedb459b8313fc89fc172560448624e54e1e6). At this point, my best bet would to be to upgrade kubectl to newer version. 

I'll update you once we make some progress.

**Comment by imuqtadir** [comment]
I figured out the issue after much dive deep for an easy fix. I'll put out PR in few minutes.

**Comment by imuqtadir** [comment]
I added more details to the PR. It was a permissions issue and pods were never really evicted successfully and were internally failing eviction. There weren't any logs within kubectl lib which made it worse to detect. You should be able to apply the fix with helm or update permissions. Thanks for bringing it to our notice.
