### ISSUE TITLE
Support ASG to SQS

### ISSUE THREAD

**Issue by foriequal0** [aws/aws-node-termination-handler#356]
It seems that ASG LifecycleHook can directly send events to SQS: (See NotificationTargetARN https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_LifecycleHook.html)

Is there any special reason to use EventBridge?

**Comment by bwagner5** [comment]
Good point!  Unfortunately, the current implementation does not support the payload body of ASG sending it directly, since it's different from EventBridge.  I think it would be an excellent feature to support though. 

```
{
  "LifecycleHookName": "test-to-sqs",
  "AccountId": "000000000000",
  "RequestId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx",
  "LifecycleTransition": "autoscaling:EC2_INSTANCE_TERMINATING",
  "AutoScalingGroupName": "my-asg,
  "Service": "AWS Auto Scaling",
  "Time": "2021-01-28T20:06:18.130Z",
  "EC2InstanceId": "i-00000000000",
  "LifecycleActionToken": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx"
}
```

**Comment by patstrom** [comment]
Is it only the data format that differs? Or are the other architectural concerns?

I am looking to deploy this project in the queue-processor mode and it would be nice to do it with as little complexity as possible. If EventBridge isn't strictly necessary I would prefer to not utilize (and pay for) it. Depending on how big of a patch this would require I could give it a go.

**Comment by foriequal0** [comment]
It seems that EventBridge exists to funnel all events in the account into a single global queue channel.
ASG to SQS only sends two kind of events: `autoscaling:EC2_INSTANCE_LAUNCHING`, `autoscaling:EC2_INSTANCE_TERMINATING`. No Spot ITN, no scheduled events, no rebalance recommendation with ASG to SQS alone, and it seems that there is no way to listen EC2 status changes.
To use it alone without EventBridge, we should make a IMDS+Queue hybrid processor. I think it'll be more complicated.

**Comment by JnMik** [comment]
Hmm.. I guess that must be why I have these errors _ignoring event due to error error="Event source () is not supported_ : 
![image](https://user-images.githubusercontent.com/4965516/118558696-016cf680-b735-11eb-8b05-02056f4a9662.png)

I have ASG > Terminate hook > SQS and I've passed the SQS Queue URL to the NTH (v1.13.0)

**Comment by Sreddy-gs** [comment]
as @JnMik mentioned i have same error logs showing up 
```
2021/07/22 14:11:47 ??? Started watching for interruption events
2021/07/22 14:11:47 ??? Kubernetes AWS Node Termination Handler has started successfully!
2021/07/22 14:11:47 ??? Started watching for event cancellations
2021/07/22 14:11:47 ??? Started monitoring for events event_type=SQS_TERMINATE
2021/07/22 14:20:05 WRN ignoring event due to error error="Event source () is not supported"
2021/07/22 14:20:05 ??? There was a problem monitoring for events error="All of the waiting queue events could not be processed" event_type=SQS_TERMINATE
```
