### ISSUE TITLE
List of available fields for webhookTemplate

### ISSUE THREAD

**Issue by adrianmiron** [aws/aws-node-termination-handler#357]

**Comment by adrianmiron** [comment]
Hi,

I am interested in getting a list of available variables i can reference in the webhookTemplate. Is there a list somewhere ? I would mostly want the ASG  name/tags/info/etc .

Right now the documentation shows 👍 
{"text":"[NTH][Instance Interruption] EventID: {{ .EventID }} - Kind: {{ .Kind }} - Instance: {{ .InstanceID }} - Description: {{ .Description }} - Start Time: {{ .StartTime }}"}

Looking through logs i can see it refence stuff like accountID, instanceType, but nothing related to the ASG.

Thanks

**Comment by bwagner5** [comment]
Currently, ASG name and tags are not available to be used in the webhook template. There's another issue out to add node labels to the webhook template as well https://github.com/aws/aws-node-termination-handler/issues/265.  I don't think it would take that much work to add these. 

The current fields you can use are:

https://github.com/aws/aws-node-termination-handler/blob/23b97f40987f52a28d533bd7bba7a391d46e7e3b/pkg/ec2metadata/ec2metadata.go#L105-L116

https://github.com/aws/aws-node-termination-handler/blob/23b97f40987f52a28d533bd7bba7a391d46e7e3b/pkg/monitor/types.go#L26-L36

and here is where those two structs are combined:
https://github.com/aws/aws-node-termination-handler/blob/23b97f40987f52a28d533bd7bba7a391d46e7e3b/pkg/webhook/webhook.go#L32-L36

**Comment by adrianmiron** [comment]
Thanks for the reply, looking forward to the new fields :)

**Comment by mmingorance-dh** [comment]
I was wondering if it would be possible to add extra tags. We for example would like to set a tag to differentiate each requests from which Kubernetes cluster come from.
Would be possible to maybe add the instance tags?

**Comment by imuqtadir** [comment]
@mmingorance-dh Currently, we are showing NodeLabels maybe you can use that? Regardless, feel free to open an issue or put out a PR for it.

**Comment by mmingorance-dh** [comment]
@imuqtadir thanks for sharing! Does that attribute allow you show just one particular label? 
Example: {{ .NodeLabels.MyLabelName }}

Also, I saw the latest release still doesn't have this attribute. When will the next release happen?

**Comment by imuqtadir** [comment]
@mmingorance-dh Yes, it does. You can refer to my PR which has some detailed examples of what you can use within webhook template related to NodeLabels. Here: https://github.com/aws/aws-node-termination-handler/pull/382

We are yet to release these changes. I'll try and get the release going in coming week.
