### ISSUE TITLE
is it possible to get list of pod names running on node after node cordoning in webhook notification?

### ISSUE THREAD

**Issue by atul-chegg** [aws/aws-node-termination-handler#359]
Use case:
We are running build jobs. Each job runs in a pod. We want to know name of pods those are going to be terminated because of any unscheduled node event so that we can restart those jobs.

**Comment by bwagner5** [comment]
NTH does log the pods that were evicted, but I assume you mean via the webhook? 

Here's an example in NTH's logs where it says that it ignores the daemonsets and evicts individual pods"
https://github.com/aws/aws-node-termination-handler/runs/1704669803#step:4:382

**Comment by atulatri** [comment]
> NTH does log the pods that were evicted, but I assume you mean via the webhook?
Yes. We want names of all the evicted pods in our slack message. Is this already possible?

**Comment by bwagner5** [comment]
Unfortunately, that is not possible currently.

**Comment by vermaabhay** [comment]
+1 
This will be something very meaningful and helpful.
