### ISSUE TITLE
Better Docs

### ISSUE THREAD

**Issue by bwagner5** [aws/aws-node-termination-handler#36]
As the node-termination-handler includes more features and configurable values, we should have some nice docs. 

I would propose https://www.mkdocs.org/ for user docs. 

Initial list of some useful sections in the docs:
1) All the different configuration values allowed and some more detail on each
2) Helm configurations
3) Using the node-termination-handler as an on-host binary (not a daemonset) - maybe baked into an AMI?

**Comment by mattrandallbecker** [comment]
self reminder to update dockerhub as well when i push my updated documentation

**Comment by mattrandallbecker** [comment]
never ending task, but just pushed an updated readme that meets the spirit of this task.  will evaluate what other updates are needed in the future as needed.
