### ISSUE TITLE
Pod get AccessDenied error

### ISSUE THREAD

**Issue by LijieZhou** [aws/aws-node-termination-handler#373]
First time install the termination handler on EKS (1.16). Followed the instruction of Queue Processor Mode. After launching, the pod gets permissiondenied error: 

```
2021/02/24 18:21:12 ??? There was a problem monitoring for events error="WebIdentityErr: failed to retrieve credentials\ncaused by: AccessDenied: Not authorized to perform sts:AssumeRoleWithWebIdentity\n\tstatus code: 403, request id: ef27c9bd-e129-44ca-bbbe-839cdcc3e840" event_type=SQS_TERMINATE
```

I did create the IAM role and attached the recommended policy. We are already using the service account, so I annotated the service account with the IAM role I created by doing this: 

```
kubectl annotate serviceaccount -n kube-system aws-node-termination-handler \
eks.amazonaws.com/role-arn=arn:aws:iam::<AWS_ACCOUNT_ID>?:role/test-termination-handler
```

I also described the pod and verified that the `AWS_WEB_IDENTITY_TOKEN_FILE ` and `AWS_ROLE_ARN` environment variables exist. 

What else could be wrong?

**Comment by LijieZhou** [comment]
The problem is solved. The issue was not using the right AWS IAM role. When creating the IAM role to associate with the service account, the right type of IAM role should be chosen. Close the issue since it is not a termination-handler related issue.

**Comment by jbuettnerbild** [comment]
@LijieZhou  What is the right type of the IAM role or where can i found it?

**Comment by david-childs** [comment]
> 

Same question - what's the right type of IAM role?
