### ISSUE TITLE
Multicluster account with multiple ASGs handle request

### ISSUE THREAD

**Issue by Angoll** [aws/aws-node-termination-handler#380]
When you have an account with multiple clusters each cluster will have different ASGs associated to it. That means if the NTH will receive events for nodes that don't belong to the cluster. It would be great to have a way to also check if managed by an EKS cluster and is that cluster.

Example scenario:
 - EKS ClusterA  with ASG_A_1, ASG_A_2   and SQS_A
 - EKS ClusterB  with ASG_B_1, ASG_B_2   and SQS_B
 - Events from: source: aws.autoscaling scoped to resources: [ ASG_A_1, ASG_A_2 ]
    target to SQS_A
 - Events from: source: aws.autoscaling scoped to resources: [ ASG_B_1, ASG_B_2 ]
    target to SQS_B
 - Events from: source: aws.ec2 ⚠️ Events from aws.ec2 can not be scoped.
    target to SQS_A and SQS_B
    
My proposal is allowing to set a value to the managed tag, so the NTH checks for the managed tag + value.
This way each EKS can run with:
  - EKS Cluster A -> NTH queueURL=SQS_A  managed-asg-tag-value=ClusterA
  - EKS Cluster B -> NTH queueURL=SQS_B  managed-asg-tag-value=ClusterB

Thanks

**Comment by Angoll** [comment]
Added a pull request with the implementation changes proposed:
https://github.com/aws/aws-node-termination-handler/pull/381

Thanks

**Comment by bwagner5** [comment]
I'm not sure matching on the tag value is necessary, why not configure the tag key to be unique per cluster?

**Comment by Angoll** [comment]
You are right, it's not necessary. I'm not sure why I was focused that the value should be used. Closing the pull request.
Thanks for your time
