### ISSUE TITLE
ASG tag checking cannot be turned off in DeamonSet

### ISSUE THREAD

**Issue by lkusnadi** [aws/aws-node-termination-handler#385]
Found in helm.sh/chart: aws-node-termination-handler-0.14.1
ASG tag checking cannot be disabled when aws-node-termination-handler is deployed as daemonset.
Seems this feature is designed for Queue processor, not IMDS.
Thank you.

**Comment by bwagner5** [comment]
Yes, that is correct. ASG tag checking can only be used with Queue Processor mode, not in IMDS mode.   There is one helm chart to make the switch between the modes as easy as possible. The config options are broken out into separate tables for the different modes starting here: https://github.com/aws/aws-node-termination-handler/tree/a25165b6d1fe3e4b6541db1d565bc9ec83cbf263/config/helm/aws-node-termination-handler#aws-node-termination-handler---imds-mode-configuration

**Comment by lkusnadi** [comment]
@bwagner5 Thanks for your response.
From looking at the helm chart, it looks like IMDS uses daemonset kind and Queue processor uses deployment kind.
When I'm using daemonset (IMDS), the pod running on the cluster shows as: 

```
...
queue-url: ,
check-asg-tag-before-draining: true,
managed-asg-tag: aws-node-termination-handler/managed,
aws-endpoint: ,
...
```

If I don't have the tag above in my ASG, does it mean NTH will not drain the pods when spot termination event happens under daemonset kind? Is there a reason why we cannot disable the ASG tag check in daemonset?

**Comment by bwagner5** [comment]
> If I don't have the tag above in my ASG, does it mean NTH will not drain the pods when spot termination event happens under daemonset kind? Is there a reason why we cannot disable the ASG tag check in daemonset?

No, when NTH is running in IMDS mode, then it will never check the ASG tag (it will never use any permissioned  AWS API calls).

**Comment by lkusnadi** [comment]
Got it. Thanks @bwagner5
