### ISSUE TITLE
Queue mode: missing AWS_REGION attempts to lookup sqs.queue.amazonaws.com and fails

### ISSUE THREAD

**Issue by james-callahan** [aws/aws-node-termination-handler#390]
If I don't set the `AWS_REGION` environment variable, then the server fails to start with:
```
RequestError: send request failed\ncaused by: Post \"https://sqs.queue.amazonaws.com/\": dial tcp: lookup sqs.queue.amazonaws.com on 172.20.0.10:53: no such host
```

This is despite the logs on startup showing me the correct `queue-url` (partially redacted):
```
queue-url: https://us-west-2.queue.amazonaws.com/MY_ACCOUNT_ID/node-termination, 
```

I've worked around this for now by setting `AWS_PROFILE=us-west-2`, but I shouldn't have to.

**Comment by bwagner5** [comment]
Agreed, we will look into this and get to the bottom of it! Thanks for submitting the issue :)

**Comment by james-callahan** [comment]
@jillmon I dont' this should be of type question, it's more of a bug; or if intentional (unlikely), it's an enhancement request.

**Comment by bwagner5** [comment]
I've submitted a PR to fix the region detection within an SQS queue url if no region was specified.  I think it should still be a best practice to set `AWS_REGION` just to be a little more explicit about it. I wouldn't expect SQS queue-urls to change much, but they could.

**Comment by bwagner5** [comment]
released
