### ISSUE TITLE
Support for Windows Server 2004

### ISSUE THREAD

**Issue by Aqilmirza** [aws/aws-node-termination-handler#397]
Could we have the support for Windows Server 2004 as EKS supports it now https://docs.aws.amazon.com/eks/latest/userguide/eks-ami-versions-windows.html

**Comment by jillmon** [comment]
Hello,

At this time support for Windows 2004 is not currently on our roadmap for this project. We did do some initial work to support a new version of Windows that we found to be generally more popular than 2004. If we were to receive a larger number of requests for expanded Windows support, then we would certainly reevaluate our roadmap priorities. In the meantime, we will continue to monitor Windows usage amongst our customers and react accordingly.
