### ISSUE TITLE
Make SQS Recieve Message Polling Configurable

### ISSUE THREAD

**Issue by tskinn** [aws/aws-node-termination-handler#398]
Is it in the roadmap to make these values configurable instead of being hard coded? https://github.com/aws/aws-node-termination-handler/blob/main/pkg/monitor/sqsevent/sqs-monitor.go#L156-L158

I would like to setup long polling for sqs. For an example of what I'm talking about https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/sqs-example-enable-long-polling.html

I'm happy to contribute if this is considered an acceptable change to be made.

**Comment by bwagner5** [comment]
I think rather than making it configurable, NTH should always use long-polling.

**Comment by bwagner5** [comment]
released
