### ISSUE TITLE
Spot nodes not labeled as such

### ISSUE THREAD

**Issue by MarcusNoble** [aws/aws-node-termination-handler#4]
I'm not seeing the `lifecycle: Ec2Spot` label associated with my nodes running on spot instances. Is there something in addition to this project that needs to run for this label to appear?

Running EKS 1.14, all nodes running on spot instances.

**Comment by mattrandallbecker** [comment]
Good catch, it appears we missed instructions on how to label your nodes.  We'll update the documentation.

In the meantime you can add labels to your nodes via:
kubectl label nodes <your-node-name> lifecycle=Ec2Spot

**Comment by MarcusNoble** [comment]
This would only be valid until a node is terminated and another replaces it though, right?

**Comment by mattrandallbecker** [comment]
Correct, using eksctl you can add nodegroups labels and using kops you can add instancegroup nodelabels to automatically add the labels to instances as they are provisioned.  We'll provide more comprehensive documentation shortly, thank you for your patience.

**Comment by MarcusNoble** [comment]
Ah! We're using Terraform to scaffold up our EKS clusters so that doesn't help. 😞

**Comment by mattrandallbecker** [comment]
found this example of node labels being applied to EKS via terraform, not sure if your setup is similar, let me know if this helps:
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/spot_instances/main.tf#L66

**Comment by MarcusNoble** [comment]
Yeah, that does help I think. I'll give it a try 😄 Thanks!

**Comment by MarcusNoble** [comment]
The `--node-labels=kubernetes.io/lifecycle=spot` will work fine for normal ASGs but won't be useable for mixed instance type ASGs. It's a shame the AWS Instance Metadata doesn't inform on the instance lifecycle being used. 😞

Do you know if there would be any adverse effects to me running this on all nodes (not just spot) by removing the `nodeSelector`?

**Comment by bwagner5** [comment]
There shouldn't be any issue running this on all nodes (both spot and on-demand). The handler will simply monitor metadata, but never be interrupted when running on an on-demand node.

**Comment by MarcusNoble** [comment]
I'm thinking I may recommend that to our teams that are running mixed instances then 🙂

**Comment by bwagner5** [comment]
We removed the node selector in `node-termination-handler.yaml` so that by default we'll run on all nodes. For a serious deployment we'd still recommend to constrain the nodes to just spot by adding a Node Selector. We'll be updating the documentation on how to do that and try to make the process as easy as possible. 

**Commit removing node selector:** https://github.com/aws/aws-node-termination-handler/commit/481dbedfafa46a7d5e7e3e92b57904bfb85f8eed

**Comment by bazimov** [comment]
We use https://github.com/kube-aws/kube-spot-termination-notice-handler, we pass extra arguments to ec2 userdata bootstrap script.

**Comment by bwagner5** [comment]
^^ more doc updates to use the recently introduced kustomize integration. Now you can override specific parts of the kubernetes resource yaml to add or modify configuration without having to completely roll your own kubernetes resource file and keep it up-to-date with our base. Hope this helps! I'm going to go ahead and close out this issue, but if you think we need more, feel free to reopen and we can discuss further.
