### ISSUE TITLE
metadataTries setting doesn't work as expected

### ISSUE THREAD

**Issue by wtchangdm** [aws/aws-node-termination-handler#406]
NTH Version: `v1.13.0` with `enableSqsTerminationDraining` on

At [Chart settings][1]:

> metadataTries: The number of times to try requesting metadata. If you would like 2 retries, set metadata-tries to 3.

However, I tried to set 2 and 10, the results are the same.

`metadataTries = 10`
```
2021/04/13 03:47:57 WRN Unable to retrieve an IMDSv2 token, continuing with IMDSv1, Put "http://169.254.169.254/latest/api/token": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2021/04/13 03:47:59 WRN Unable to retrieve an IMDSv2 token, continuing with IMDSv1, Put "http://169.254.169.254/latest/api/token": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2021/04/13 03:48:01 WRN Unable to retrieve an IMDSv2 token, continuing with IMDSv1, Put "http://169.254.169.254/latest/api/token": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2021/04/13 03:48:03 WRN Unable to retrieve an IMDSv2 token, continuing with IMDSv1, Put "http://169.254.169.254/latest/api/token": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2021/04/13 03:48:03 INF Startup Metadata Retrieved metadata=...(redacted)
...(redacted)
metadata-tries: 10,
```

`metadataTries = 2`
```
2021/04/13 03:44:50 WRN Unable to retrieve an IMDSv2 token, continuing with IMDSv1, Put "http://169.254.169.254/latest/api/token": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2021/04/13 03:44:52 WRN Unable to retrieve an IMDSv2 token, continuing with IMDSv1, Put "http://169.254.169.254/latest/api/token": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2021/04/13 03:44:54 WRN Unable to retrieve an IMDSv2 token, continuing with IMDSv1, Put "http://169.254.169.254/latest/api/token": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2021/04/13 03:44:56 WRN Unable to retrieve an IMDSv2 token, continuing with IMDSv1, Put "http://169.254.169.254/latest/api/token": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2021/04/13 03:44:56 INF Startup Metadata Retrieved metadata=...(redacted)
...(redacted)
metadata-tries: 2,
```

Please let me know if further information is needed. Thanks!

[1]: https://github.com/aws/aws-node-termination-handler/tree/main/config/helm/aws-node-termination-handler#aws-node-termination-handler-common-configuration

**Comment by brycahta** [comment]
Thanks for opening the issue @wtchangdm. 

On a first pass, my guess is there's an issue with the logic starting [here](https://github.com/aws/aws-node-termination-handler/blob/4a370232d42826a7081cee9d90a80acb9969815c/pkg/ec2metadata/ec2metadata.go#L219).

The [tokenRetryAttempts](https://github.com/aws/aws-node-termination-handler/blob/4a370232d42826a7081cee9d90a80acb9969815c/pkg/ec2metadata/ec2metadata.go#L60) is a separate, non-configurable value that isn't influenced by `metadataTries` config.

Will revisit when I get some time, but this is a good starting point

**Comment by bwagner5** [comment]
I think this is working as intended. The metadata tries shouldn't have a configurable retry on token fetching. It only affects retries after a token is retrieved or if querying w/ IMDSv1. We always try IMDSv2 first, but it should fail fast if it's not enabled or is blocked due to the hop count when not running w/ Host Networking or is intentionally blocked by some other system to prevent containers from querying IMDS.

**Comment by wtchangdm** [comment]
Thanks for the reply, @brycahta, @bwagner5.

Actually, we are using IRSA for NTH but [haven't tweak IMDS access][1] from the launch template default due to other workloads' need.

I haven't checked the code yet, but if NTH needs metadata does it mean once we restrict IMDSv1 & v2, we have to put NTH to `hostNetork: true`? (Otherwise NTH may need some code changes and additional permission to describe instance attribute)

[1]: https://docs.aws.amazon.com/eks/latest/userguide/best-practices-security.html#restrict-ec2-credential-access

**Comment by bwagner5** [comment]
@wtchangdm sorry for the delayed reply!  If you're using sqsTerminationDraining (queue-processor mode) then you do not need access IMDS at all.

**Comment by stevehipwell** [comment]
@bwagner5 in queue-processor mode you still get an error if you can't access IMDS, so this might want updating or calling out specifically?
