### ISSUE TITLE
`InterruptionEvent.Drained` leads to confusion

### ISSUE THREAD

**Issue by cucxabong** [aws/aws-node-termination-handler#407]
At first, I think this property mean that all Pod has been drained or whether or not pod should be drained. But this is something to told that an event has been processed or not. I think we should rename this to something like `InterruptionEvent.Processed` or `InterruptionEvent.Done`. What do you think about this?

**Comment by haugenj** [comment]
I agree it's a bit confusing, but it doesn't exactly mean that the event has been processed either. The intention is that we [avoid multiple drain calls](https://github.com/aws/aws-node-termination-handler/blob/main/pkg/interruptioneventstore/interruption-event-store.go#L111-L120) for the same node, so it's more of a reference to the node associated with an event than the event itself. Perhaps `InterruptionEvent.NodeDrained` or `.NodeProcessed` or something like that would be better. Would you like to contribute a refactor for this?
