### ISSUE TITLE
SQSMonitor::Monitor doesn't delete unwanted messages

### ISSUE THREAD

**Issue by tyrken** [aws/aws-node-termination-handler#408]
Trying out the latest release (v1.13.0) in SQS mode again - but our account has other spot instances that are not in the EKS cluster, and EventBridge is sending all spot-instance terminations to the queue.  (There doesn't seem any way of limiting this in scope - as I'm trying to do for the ASG hooks elsewhere.)

I'm using a `managedAsgTag: kubernetes.io/cluster/<cluster-name>` override to make NTH only consider messages for it's own nodes, which is causing `isManaged` to correctly print a message to Debug logs, returning nil/nil I therefore suspect.  But from my reading of the Monitor function it isn't written to do anything special with that return, so it just keeps ignoring & then re-trying the message when the visibility times out.

Eventually it writes an error message about the instance not existing after it's terminated, and so gets an error and deletes the message with "dropping event for an already terminated node" logged.

I think we should assume the SQS queue is owned by NTH and so it deletes the foreign & to-be-ignored message as soon as it realises it's not `isManaged`.

**Comment by haugenj** [comment]
> (There doesn't seem any way of limiting this in scope - as I'm trying to do for the ASG hooks elsewhere.)

Yep that's how it looks to me as well. You should be able to restrict the ASG Lifecycle events that get sent to the queue via pattern matching on the ASG arn, but for Spot ITNs and EC2 Rebalance Recs it seems impossible. 

> I think we should assume the SQS queue is owned by NTH and so it deletes the foreign & to-be-ignored message as soon as it realises it's not isManaged.

This seems like a reasonable assumption to make. Doing this will force people to create separate queues per cluster, and new targets for the event rules, but that seems alright imo. We might want to call this out in the documentation, and definitely in the release notes as that could break backwards compatibility for anyone running a setup with the same queue for multiple clusters

I can take this up

**Comment by tyrken** [comment]
Can I please bump this up, for at least documentation purposes, as I think queue-per-cluster is not merely "alright" but strongly recommended & should be presumed in any examples.

If you have multiple clusters all on one queue & the wrong cluster gets the message first, you have to wait for SQS visibility timeout (default 30 seconds, but can be lower) before the right cluster gets a second chance to act.  It can then lose the race a second or third time...
