### ISSUE TITLE
Does this work with IAM for service account using OIDC on EKS if ec2 instance metadata endpoint is blocked?

### ISSUE THREAD

**Issue by alexmnyc** [aws/aws-node-termination-handler#425]
Does this work with IAM for service account using OIDC on EKS if ec2 instance metadata endpoint is blocked?

I.e.
```
# commands block ALL containers from using the instance profile credentials
yum install -y iptables-services
iptables --insert FORWARD 1 --in-interface eni+ --destination 169.254.169.254/32 --jump DROP
iptables-save | tee /etc/sysconfig/iptables
systemctl enable --now iptables
```

**Comment by bwagner5** [comment]
If you're trying to use IMDS mode, then IMDS need to be accessible to the container.  I'm not sure if the above would block NTH running IMDS mode in HostNetworking mode or not (it looks like it would though, you can test by attempting to curl IMDS on the host itself).  

If you'd like to use queue-processor mode of NTH, then IMDS is not required at all.
