### ISSUE TITLE
Use more structured logging format

### ISSUE THREAD

**Issue by james-callahan** [aws/aws-node-termination-handler#436]
Currently log messages come out as e.g.
> `2021/05/19 00:41:58 INF Adding new event to the event store event={"some":"json"}`

This is non trivial to parse out e.g. the json object.

Could you use a more structured logging format such as [logfmt](https://brandur.org/logfmt)? (which is well supported by e.g. [loki](https://grafana.com/docs/loki/latest/logql/#logfmt))

[github.com/go-logfmt/logfmt](https://github.com/go-logfmt/logfmt) appears to be a popular Go library for it.

**Comment by haugenj** [comment]
We have an config parameter `jsonLogging` for formatting the logs in json format, such as `{"level":"info","time":"2021-05-19T15:54:20Z","message":"Started watching for interruption events"}`. Does that cover what you need?

**Comment by james-callahan** [comment]
Ah thanks! yes, json logging is sufficient.

I think logfmt support would be good too, but am happy to close this if you don't want to add that feature.

**Comment by bwagner5** [comment]
I'll close this issue for now, but feel free to post back with any benefits of using logfmt vs. zerolog and we can reassess whether it's worth opening the issue again.
