### ISSUE TITLE
Delete nodes when they are killed/interrupted

### ISSUE THREAD

**Issue by james-callahan** [aws/aws-node-termination-handler#437]
Occasionally we're seeing notifications with no notice:

> `2021/05/19 00:39:38 INF Adding new event to the event store event={"AutoScalingGroupName":"myasg","Description":"ASG Lifecycle Termination event received. Instance will be interrupted at 2021-05-19 00:39:37 +0000 UTC \n","Drained":false,"EndTime":"0001-01-01T00:00:00Z","EventID":"asg-lifecycle-term-someID","InProgress":false,"InstanceID":"i-1234567890","Kind":"SQS_TERMINATE","NodeLabels":null,"NodeName":"ip-xx-xx-xx-xx.us-west-2.compute.internal","Pods":null,"StartTime":"2021-05-19T00:39:37Z","State":""}`

That node became unreachable from the kubernetes control plane; and sat there:
```
Conditions:
  Type             Status    LastHeartbeatTime                 LastTransitionTime                Reason              Message
  ----             ------    -----------------                 ------------------                ------              -------
  MemoryPressure   Unknown   Tue, 18 May 2021 14:01:01 -0700   Tue, 18 May 2021 14:03:46 -0700   NodeStatusUnknown   Kubelet stopped posting node status.
  DiskPressure     Unknown   Tue, 18 May 2021 14:01:01 -0700   Tue, 18 May 2021 14:03:46 -0700   NodeStatusUnknown   Kubelet stopped posting node status.
  PIDPressure      Unknown   Tue, 18 May 2021 14:01:01 -0700   Tue, 18 May 2021 14:03:46 -0700   NodeStatusUnknown   Kubelet stopped posting node status.
  Ready            Unknown   Tue, 18 May 2021 14:01:01 -0700   Tue, 18 May 2021 14:03:46 -0700   NodeStatusUnknown   Kubelet stopped posting node status.
```
Kubernetes is unsure whether the node became unreachable over the network vs was terminated.

Could the node termination handler gain the feature to tell kubernetes that the node is *not* just network unreachable and is likely to not come back? e.g. by deleting the node?

**Comment by bwagner5** [comment]
The aws cloudprovider should take care of deleting the node in k8s once it's been terminated in EC2. I'm not sure why it did not in your case. We're pretty hesitant about deleting nodes in NTH in case they became orphaned (running in EC2 but deleted in k8s).

**Comment by james-callahan** [comment]
> The aws cloudprovider should take care of deleting the node in k8s once it's been terminated in EC2. I'm not sure why it did not in your case. 

How does the cloudprovider know such a thing for self-managed nodes?

> We're pretty hesitant about deleting nodes in NTH in case they became orphaned (running in EC2 but deleted in k8s).

This issue is about when the EC2 node has already been deleted but the k8s node hasn't been.

Currently we have to wait 1 hour for the (non-responding) node to be removed; meanwhile any pods scheduled to those nodes are... missing.

**Comment by brandond** [comment]
We have a number of uses cases where we operate auto-scaling groups without the AWS cloudprovider. It'd be great if the NTH could handle deleting terminated nodes without requiring deployment of the full cloudprovider.

**Comment by james-callahan** [comment]
> We definitely have to wait for the node to be terminated in EC2 since we don't ever want to orphan a running ec2 instance.

I'm requesting the opposite: when a node is orphaned in k8s (i.e. the EC2 node is deleted; but the k8s node remains), something needs to clean up the node.

**Comment by brandond** [comment]
Often times I don't need all the overhead (both in terms of iam roles, tagging, etc and in terms of deployed components) that come with the cloud provider. I don't need any of the load balancer or instance management stuff, I just want nodes to get cleaned up properly when they're terminated.

**Comment by brandond** [comment]
not stale, still wanted.
