### ISSUE TITLE
PSP RoleBinding roleRef is incorrect

### ISSUE THREAD

**Issue by gabegorelick** [aws/aws-node-termination-handler#441]
https://github.com/aws/aws-node-termination-handler/pull/435 updated `aws-node-termination-handler-psp` from a `ClusterRole` to a `Role`, but the corresponding `RoleBinding` wasn't updated:

https://github.com/aws/aws-node-termination-handler/blob/e617cc3f79a29912d76231d15d139de98455ea23/config/helm/aws-node-termination-handler/templates/psp.yaml#L35-L59

That `roleRef` probably shouldn't refer to a `ClusterRole`.

**Comment by bwagner5** [comment]
Whoops! You are right!

**Comment by haugenj** [comment]
reopening until the release

**Comment by jgournet** [comment]
Might be too early to complain about this, but when upgrading via helm, I'm getting this error:
```
Error: cannot patch "aws-node-termination-handler-psp" with kind RoleBinding: RoleBinding.rbac.authorization.k8s.io "aws-node-termination-handler-psp" is invalid: roleRef: Invalid value: rbac.RoleRef{APIGroup:"rbac.authorization.k8s.io", Kind:"Role", Name:"aws-node-termination-handler-psp"}: cannot change roleRef
```
Am I doing something wrong ? 

ps: I'm upgrading from:
appVersion: 1.13.0
to 
appVersion: 1.13.1

**Comment by bwagner5** [comment]
The upgrade may not work properly because we changed it from a cluster role to a role. I'm guessing helm doesn't know how to deal with that... You may have to do an uninstall and reinstall. Not optimal, but that should work.
