### ISSUE TITLE
v1.13.2 image missing

### ISSUE THREAD

**Issue by james-callahan** [aws/aws-node-termination-handler#470]
https://github.com/aws/aws-node-termination-handler/releases/tag/v1.13.2

> Error response from daemon: manifest for public.ecr.aws/aws-ec2/aws-node-termination-handler:v1.13.2 not found: manifest unknown: Requested image not found

**Comment by stevehipwell** [comment]
It looks like the [GH actions](https://github.com/aws/aws-node-termination-handler/actions) are failing for the tag.

**Comment by stevehipwell** [comment]
@bwagner5 I assume that this is why the Helm chart hasn't been merged over to [aws/eks-charts](https://github.com/aws/eks-charts) and released?

**Comment by bwagner5** [comment]
Yes, gha failure is holding up release right now. We recently changed some stuff behind the deployment that needs a little tuning, but we will get it out today! Apologies for the delay!

**Comment by james-callahan** [comment]
Appears to exist now.
```
$ docker pull public.ecr.aws/aws-ec2/aws-node-termination-handler:v1.13.2
v1.13.2: Pulling from aws-ec2/aws-node-termination-handler
3c8ccab02ec8: Pull complete 
ae39874320ef: Pull complete 
cba773dc080f: Pull complete 
Digest: sha256:2fdf61364181feb0e4c0754a838b865c51837e389361ed0d163c8a7e6f16dd9f
Status: Downloaded newer image for public.ecr.aws/aws-ec2/aws-node-termination-handler:v1.13.2
public.ecr.aws/aws-ec2/aws-node-termination-handler:v1.13.2
```
