### ISSUE TITLE
Pods were scheduled to a node ready to be terminated

### ISSUE THREAD

**Issue by wtchangdm** [aws/aws-node-termination-handler#476]
Hi, I am using queue processor mode with `1.3.2` image, which was installed via helm chart version `0.5.2`

Long story short: we have a self-managed node group using ASG and constantly scale out/in every hour.
A few hours ago, it scaled in and removed a few instances as usual, but we noticed some pods (let's call it service A) are not drained and caused some HTTP 5xx.

After some investigation, I noticed that these Service A's pods were running on an instance, say, i-12345678.

The following infomation are gathered from ASG console and NTH logs:

ASG activity said: 

```
At 2021-07-29T04:30:38Z instances were launched to balance instances in zones ap-northeast-1a ap-northeast-1c with other zones resulting in more than desired number of instances in the group.
At 2021-07-29T04:31:00Z an instance was taken out of service in response to a difference between desired and actual capacity, shrinking the capacity from 17 to 16.
At 2021-07-29T04:31:00Z instance i-12345678 was selected for termination.
```

NTH's log said:

```
2021/07/29 04:31:02 INF Adding new event to the event store event={"AutoScalingGroupName":"SOME_RANDOM_ASG_NAME","Description":"ASG Lifecycle Termination event received. Instance will be interrupted at 2021-07-29 04:31:01 +0000 UTC \n","EndTime":"0001-01-01T00:00:00Z","EventID":"asg-lifecycle-term-61313936666330312345678qqqqq73263652d393939636666663766313438","InProgress":false,"InstanceID":"i-12345678","Kind":"SQS_TERMINATE","NodeLabels":null,"NodeName":"ip-10-1-2-3.ap-northeast-1.compute.internal","NodeProcessed":false,"Pods":null,"StartTime":"2021-07-29T04:31:01Z","State":""}
```

I think the story is:

1. Our scheduled heavy workload (service B) is finished. The HPA reduced the replicas.
2. Service B's pods are terminated and cluster autoscaler is shrinking the ASG.
3. According to the ASG activity log, instance i-12345678 was chosen to terminate in order to match the desired number.
4. According to the NTH log, when NTH received the event, there was no pod on it (see `"Pods":null`), so looked like no cordon/draining was invoked.
5. Cluster Autoscaler tried to kick Service A's pods to other instances so It can reduce ASG's desire number.
6. Service A's pods seem to be created on instance i-12345678 and started running.
7. NTH completed the ASG lifecycle hook and the instance was terminated. And the Service A's pods didn't get the chance the perform graceful shutdown.

This seems to be a corner case, but I am wondering is there any way to prevent this kind of issue?

Thanks.

**Comment by bwagner5** [comment]
Even if no pods are on a node, NTH will Cordon and Drain anyways, so I'm thinking there might be another issue here.  

I'm wondering if this is related to https://github.com/aws/aws-node-termination-handler/issues/477 where the Patch permission isn't given to Events right now? Is there a WRN in the log similar to #477?

**Comment by wtchangdm** [comment]
@bwagner5 Thanks for the reply!

Unfortunately, I didn't notice such warnings back then If I recall correctly. 

This issue happened a few more times for the same reason. Since it's the production environment, I ended up setting "protected from scale in" for the ASG, then let Cluster Autoscaler do the work.

**Comment by mrsiejas** [comment]
@wtchangdm Try changing log verbosity to debug, not sure if these errors are otherwise visible in logs.
```
'logLevel': 'DEBUG'
```

**Comment by wtchangdm** [comment]
@mrsiejas Thank you for the suggestion. This issue doesn't happen frequently, I might need to figure out how to reproduce it effectively (and not on production, of course).
