### ISSUE TITLE
Slack notification support

### ISSUE THREAD

**Issue by jhedev** [aws/aws-node-termination-handler#5]
We are running several EKS clusters on spot instances. So far we are using https://github.com/kube-aws/kube-spot-termination-notice-handler to handle node termination but would love to switch to this project. 

However, we need support for slack notifications. 

/cc @ecktom

**Comment by mattrandallbecker** [comment]
Was thinking about this one and I think we'll try to provide a generic webhook solution similar to the one provided by GIthub.  I'll keep this thread updated as we make progress, thanks for the suggestion!

**Comment by m0rganic** [comment]
@mattrandallbecker Should I create a separate issue for integration to Alertmanager or were you thinking that would be included in the scope of the webhook solution?

**Comment by mattrandallbecker** [comment]
I'm not familiar with Alertmanager notifications specifically, if you want to link me to some documentation I'll take a look.

Ideally my hope was that we could implement a generic notification system that relies on a HTTPS post to a url with an optionally configured secret/api key.  We use Amazon Chime internally at Amazon and I think the proposed system works for that and Slack at a minimum.  One of our goals for the project is comprehensive integration tests so we are thinking about how to test this as well.

**Comment by m0rganic** [comment]
You can find info on the API here https://github.com/prometheus/alertmanager#api ..  prometheus is popular monitoring and timeseries solution for many k8s deployments. I can't see a reason why the solution you are describing wouldn't work with this. 

Another challenge we've been facing is getting more metadata on the EC2 instance that is getting terminated. It would be nice to know basic information about the instance that is getting terminated beyond the EC2instanceId, like how long it's been running and the AWS Action/Reason for the termination. If you could include that in your initial requirements for alerting it would be really nice.  :)

**Comment by mattrandallbecker** [comment]
I've created a PR to address this here: https://github.com/aws/aws-node-termination-handler/pull/54

Let me know if this doesn't meet any of your needs.  I tested Slack and Chime, it should in theory also work with HipChat/WeChat/etc.

**Comment by mattrandallbecker** [comment]
resolved with release 1.2.0 https://github.com/aws/aws-node-termination-handler/releases/tag/v1.2.0
