### ISSUE TITLE
Docs for supporting encrypted SQS queues

### ISSUE THREAD

**Issue by riisi** [aws/aws-node-termination-handler#526]
**Describe the feature**
It might be helpful to add docs for how to set this up with encrypted SQS queues, or at least a note that this will cause issues.

I wanted to raise this issue for anyone else having this problem - apologies if this is not the right place. 

**Is the feature request related to a problem?**
We encrypted the queue after initially setting up and testing the configuration and did not realise this would impact both the delivery of ASG -> Cloudwatch events, and SQS -> node termination handler messages.

The additional configuration required is:

Key policy for allowing Cloudwatch Events to post to the queue.
https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/CWE_Troubleshooting.html#SQSEncrypted

An additional statement on the IAM role for the pod, e.g. 
```json
    {
      "Effect": "Allow",
      "Action": [
        "kms:Decrypt"
      ],
      "Resource": [ "*" ]
    }
```

**Comment by bdwyertech** [comment]
Does anyone know how to leverage the regular SSE with this enabled instead of a CMK?

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sqs_queue#server-side-encryption-sse
