### ISSUE TITLE
Cluster With On-Demand And Spot Instances

### ISSUE THREAD

**Issue by AmitThakkar** [aws/aws-node-termination-handler#53]
I am creating an EKS cluster with On-Demand and Spot Instances. This module run a pod on on-demand instances as well. There should be a way to run pods only on spot instances.

**Comment by jillmon** [comment]
You can use the nodeSelector option in the helm chart to target pods to only spot instances by using tags. The nodeSelector is explained in the helm README https://github.com/aws/eks-charts/tree/master/stable/aws-node-termination-handler.
