### ISSUE TITLE
error when waiting for pod ... terminating: global timeout reached

### ISSUE THREAD

**Issue by gabegorelick** [aws/aws-node-termination-handler#535]
**Describe the bug**
NTH seems to timeout cordoning and draining nodes if a pod isn't evicted after a timeout. Once this happens, NTH doesn't seem to complete the calling ASG lifecycle hook (I'm in queue processor mode), and it's left to timeout. The pods do eventually terminate after the timeout.

The timeout seems to be enforced in k8s's draining code (https://github.com/kubernetes/kubernetes/blob/766a7e2e00ea42d17acb7a4cc66b8d9f579bce60/staging/src/k8s.io/kubectl/pkg/drain/drain.go#L435 or thereabouts). Not exactly sure which timeout this is ~(maybe `pod-eviction-timeout`?)~ EDIT: it's NTH's `NODE_TERMINATION_GRACE_PERIOD`, but nevertheless NTH should more gracefully handle it instead of leaving the ASG lifecycle hook to timeout, which can take a long time.

**Steps to reproduce**
Still working on a minimum test case.

**Expected outcome**
No timeout, or retry when timeout occurs

**Application Logs**
```
{"time":"2021-11-18T16:52:18Z","message":"error when evicting pods/\"pgbouncer-6b86c58dc5-7r9pc\" -n \"default\" (will retry after 5s): Cannot evict pod as it would violate the pod's disruption budget."}
{"time":"2021-11-18T16:52:23Z","message":"evicting pod default/pgbouncer-6b86c58dc5-7r9pc"}
{"time":"2021-11-18T16:52:23Z","message":"error when evicting pods/\"pgbouncer-6b86c58dc5-7r9pc\" -n \"default\" (will retry after 5s): Cannot evict pod as it would violate the pod's disruption budget."}
{"time":"2021-11-18T16:52:28Z","message":"evicting pod default/pgbouncer-6b86c58dc5-7r9pc"}
{"level":"warn","error":"node: 'i-XXXXXX' in state 'terminated': node metadata unavailable","time":"2021-11-18T16:52:29Z","message":"dropping interruption event for an already terminated node"}
{"level":"error","error":"error when waiting for pod \"pgbouncer-6b86c58dc5-7r9pc\" terminating: global timeout reached: 2m0s","time":"2021-11-18T16:52:38Z","message":"There was a problem while trying to cordon and drain the node"}
```

**Environment**

* NTH App Version: 1.14.0
* NTH Mode (IMDS/Queue processor): queue processor
* OS/Arch: Linux x64 (Bottlerocket)
* Kubernetes version: 1.21
* Installation method: Helm chart

**Comment by bwagner5** [comment]
👍 agreed, NTH should complete the lifecycle hook if a node-termination-grace-period times out. Ideally the pod termination grace period should forcefully kill the pods (SIGKILL) that breach that grace period and so it should be safe to complete the ASG lifecycle hook when breaching the node termination grace period.

**Comment by gabegorelick** [comment]
Given the current behavior, is there any reason not to set `NODE_TERMINATION_GRACE_PERIOD` arbitrarily high to ensure that NTH completes ASG lifecycle hooks?

**Comment by gabegorelick** [comment]
>  Ideally the pod termination grace period should forcefully kill the pods (SIGKILL) that breach that grace period

In my case, my pods had a grace period of 5m, while NTH's `NODE_TERMINATION_GRACE_PERIOD` was the default 2m. So I guess that's my fault for not increasing `NODE_TERMINATION_GRACE_PERIOD`.
