### ISSUE TITLE
Support labeling nodes

### ISSUE THREAD

**Issue by gabegorelick** [aws/aws-node-termination-handler#538]
**Describe the feature**
NTH currently supports cordoning nodes and tainting nodes, but it doesn't provide a way to add labels to nodes in response to a termination event.

**Is the feature request related to a problem?**
I want to be able to use nodeAffinity so that pods prefer to be scheduled on nodes that aren't being terminated, but can still be scheduled on terminating nodes if there's no alternative. 

**Describe alternatives you've considered**
Tolerate the `Unschedulable` taint, but I don't think there's a way to specify a preference for nodes without such a taint?

**Comment by brycahta** [comment]
That sounds like a useful feature and aligns with k8s recommended approaches on using label selectors for scheduling. Did you have an implementation in mind you could PR to discuss in detail (i.e. config name, label on all activity?, label removal scenarios, etc.)?

**Comment by gabegorelick** [comment]
> Did you have an implementation in mind you could PR to discuss in detail (i.e. config name, label on all activity?, label removal scenarios, etc.)?

Nope, just an idea 😄 

I think this makes a lot of sense in the context of https://github.com/aws/aws-node-termination-handler/issues/537. If NTH were to mark all nodes in a cluster as unscheduleable before it starts draining, then that can lead to a position where you can't schedule any emergency pods. So in that case, labeling instead of tainting nodes would be safer.
