### ISSUE TITLE
Provide setup instructions in Teraform

### ISSUE THREAD

**Issue by dmerrick** [aws/aws-node-termination-handler#544]
**Describe the feature**

It would be great if the required infra setup was provided in a format that could be deployed without individual commands. 

Please add some infrastructure-as-code examples in something like Teraform or CloudFormation

**Is the feature request related to a problem?**

Right now your users cant check the required setup into source control

**Describe alternatives you've considered**

Others might want different IaC software examples

**Comment by brycahta** [comment]
Hi @dmerrick, that'd be a great addition to the documentation. Were you thinking IaC to deploy all of NTH or just the artifacts necessary for Queue Processor mode? If you had something in mind feel free to PR and we can collab!
