### ISSUE TITLE
Add documentation in using Queue Processor with Karpenter

### ISSUE THREAD

**Issue by aldredb** [aws/aws-node-termination-handler#547]
**Describe the feature**
I'm using NTH with Karpenter. Since Karpenter does not use ASG, I require documentation in using Queue Processor with Karpenter e.g. using `ASSUME_ASG_TAG_PROPAGATION`

**Is the feature request related to a problem?**
N/A

**Describe alternatives you've considered**
N/A

**Comment by stevehipwell** [comment]
I thought Karpenter dealt with it's own node lifecycle? @ellistarn @bwagner5 should be able to answer this definitively.

**Comment by aldredb** [comment]
@stevehipwell As of now, Karpenter need to rely on NTH for spot interruption handling

**Comment by stevehipwell** [comment]
@aldredb I thought that was a pre GA priority but you're right (https://github.com/aws/karpenter/issues/702).

**Comment by bwagner5** [comment]
Karpenter does not handle Spot ITNs with the full 2 minutes to drain workloads. It also doesn't handle Rebalance Recommendations which would give workloads longer to drain. Karpenter does cordon and drain nodes when an operator deletes a nodes w/ kubectl or Karpenter itself terminates a node due to no pods running on it.  But Karpenter will not react to AWS terminating a node like in the case of Spot ITNs. 

We are still looking to add spot handling natively to Karpenter, but NTH will need to be installed for now.

**Comment by bwagner5** [comment]
I think we should add the docs to Karpenter instead of NTH since Karpenter has a nicer docs site.  Once we get it into Karpenter, we can link it off of NTH's docs.

**Comment by sidewinder12s** [comment]
I've got a custom autoscaler as well, this would be useful to document since it should be similar requirements.

**Comment by olemarkus** [comment]
I am curious why you wouldn't want NTH to deal with spot terminations also together with karpenter? Karpenter's area of responsibility within a cluster is already pretty huge for a controller and I think NTH does its job pretty well.

**Comment by olemarkus** [comment]
Most clusters will be mixed Karpenter and CAS-based anyway given that most people cannot run Karpenter on the Control Plane, so NTH is most likely needed anyway.

**Comment by tamirhad** [comment]
When using NTH with SQS queue, ENABLE_SPOT_INTERRUPTION_DRAINING is always false when deploying with helm. 
Is it expected? It's not something we need to be true?

**Comment by stevehipwell** [comment]
@tamirhad this is expected as I replied on the other thread that you asked this question on. Despite some AWS docs referring to this value when also specifying queue mode, `ENABLE_SPOT_INTERRUPTION_DRAINING` is only used for IMDS mode.

**Comment by universam1** [comment]
can we reopen this issue please? I actually have issues to properly configure NTH for Karpenter nodes #654

**Comment by snay2** [comment]
As @bwagner5 [mentioned](https://github.com/aws/aws-node-termination-handler/issues/547#issuecomment-994866062), this would fit better in the Karpenter documentation.

I have opened an issue on the Karpenter repo and recommend that the discussion continue there: https://github.com/aws/karpenter/issues/2159
