### ISSUE TITLE
Use a lease to promote a leader when multiple NTH replicas have been provisioned

### ISSUE THREAD

**Issue by stevehipwell** [aws/aws-node-termination-handler#549]
**Describe the feature**
I'd like NTH to use leadership election via a lease as is done in Kubernetes operators so we can have multiple replicas for HA but only one active instance.

**Is the feature request related to a problem?**
When running NTH in HA mode we need multiple replicas but this means multiple instances of NTH are processing the queue and stops a NTH instance have full control.

**Describe alternatives you've considered**
Running a single replica but this can cause NTH to become unscheduled during high levels of node churn.

**Comment by stevehipwell** [comment]
@bwagner5 I suspect this would be needed for future NTH improvements if terminations were being managed with knowledge of all events but it'd be really useful with the current version too.

**Comment by bwagner5** [comment]
Yes! We have a tentative plan to use more standard tooling for building NTH into an actual k8s controller which would use a KCM lease.

**Comment by stevehipwell** [comment]
@bwagner5 would it take much effort to add this to the current codebase?

Is there anywhere to view or contribute to the future NTH plans?
