### ISSUE TITLE
SNS Support for SQS Fanout

### ISSUE THREAD

**Issue by danquack** [aws/aws-node-termination-handler#553]
**Describe the feature**
If you set the target rule to send to SNS instead of SQS, the analyzed body is wrapped inside the message, and the SQS monitor doesn't know how to parse that.
https://github.com/aws/aws-node-termination-handler/blob/main/pkg/monitor/sqsevent/sqs-monitor.go

Specific attributes are presented to the SQS, such as TopicArn, that make it known that the source was SNS. Adding parser could make it so you could fan out the event bridge message. Although event bridge allows you to apply five targets to a rule, it doesn't guarantee order or other benefits to SNS.

This feature may also be helpful/relatable to design with #356.

**Describe alternatives you've considered**
This is an alternative design approach, instead of going directly to SQS.

**Comment by bwagner5** [comment]
Thanks for bringing this up! I think this would be a good thing to implement for NTH. I'll have to look into it and see what would be required and come up with pros and cons. 

Is there a specific use-case for needing ordering or other benefits that SNS provides that SQS would not?

**Comment by danquack** [comment]
Max subscriptions per rule is another, although you could work around that with expanding the soft limit but SNS gives you more subscriptions on a technicality. This doesn't match my use case, but it could be for someone else.
