### ISSUE TITLE
Release Cadance?

### ISSUE THREAD

**Issue by danquack** [aws/aws-node-termination-handler#561]
I'm wondering if there are any projections for the next release? It seems the last one was in October, and there have been 10+ PRs merged. Is this module released on a cadence, or is there a roadmap for when the next release will occur?

**Comment by snay2** [comment]
Thanks for asking! We don't have a set cadence or release schedule, but we do typically release more frequently than the three months it has been now.

The cause for delay this time was that we ran into some issues with publishing our container images to our [ECR repo](https://gallery.ecr.aws/aws-ec2/aws-node-termination-handler) that took longer to resolve than we expected. That should be done this week, and we're targeting an NTH release right after that.

**Comment by snay2** [comment]
Working on releasing `v1.14.1` this week: https://github.com/aws/aws-node-termination-handler/pull/565

**Comment by danquack** [comment]
@snay2  i am not seeing version 1.14 release to the helm repository:
 `curl -sS https://aws.github.io/eks-charts/index.yaml | yq e '.entries.aws-node-termination-handler.[].appVersion' -`. Am i missing something?

**Comment by snay2** [comment]
You're right, I spoke too soon. The release of `v1.14.1` to eks-charts was pending this PR: https://github.com/aws/eks-charts/pull/675. I had Brandon merge it.

You should see `v1.14.1` now:

```
% curl -sS https://aws.github.io/eks-charts/index.yaml | yq e '.entries.aws-node-termination-handler.[].appVersion' - | head
1.14.1
1.14.0
1.13.4
1.13.3
1.13.2
1.13.1
1.13.0
1.12.2
1.12.1
1.12.0
```
