### ISSUE TITLE
NTH doesn't complete lifecycle hooks for instances that failed to join cluster

### ISSUE THREAD

**Issue by gabegorelick** [aws/aws-node-termination-handler#575]
**Describe the bug**

I have ASG lifecycle hooks backed by NTH running in queue processor mode. If a node fails to join the cluster, our deploy infrastructure will eventually terminate it. However, NTH refuses to complete lifecycle hooks for instances that don't belong to the cluster. That means that the lifecycle hooks time out. 

This is despite the fact that NTH pods are running on other, healthy nodes in the cluster (I would totally understand if NTH failed to complete lifecycle hooks because NTH wasn't running 😄).

**Steps to reproduce**

1. Configure NTH in queue processor mode
2. Set up ASG lifecycle hooks
3. Deploy everything with CloudFormation `AutoScalingReplacingUpdate` so that new nodes are spun up in a new ASG that gets deleted upon deploy failure
4. Deploy an update that causes nodes to fail to join the cluster, e.g. remove the cluster info from your LaunchTemplate
5. Have CloudFormation roll back, or manually delete the ASG
6. ASG deletion triggers lifecycle hooks
7. NTH complains that "node 'XXXX' not found in the cluster"
8. ASG lifecycle hooks time out eventually and instances eventually terminate 

**Expected outcome**

I understand that NTH shouldn't try to drain or cordon nodes that don't belong to a cluster, but it should still complete any lifecycle hooks.

**Application Logs**
```
{"level":"info","event":{"EventID":"ec2-state-change-event-XXX","Kind":"SQS_TERMINATE","Description":"EC2 State Change event received. Instance i-XXX went into shutting-down at 2022-02-07 16:23:57 +0000 UTC \n","State":"","AutoScalingGroupName":"XXX","NodeName":"XXX","NodeLabels":null,"Pods":null,"InstanceID":"i-XXX","IsManaged":true,"StartTime":"2022-02-07T16:23:57Z","EndTime":"0001-01-01T00:00:00Z","NodeProcessed":false,"InProgress":false},"time":"2022-02-07T16:23:58Z","message":"Adding new event to the event store"}
{"level":"info","event-id":"ec2-state-change-event-XXX","kind":"SQS_TERMINATE","node-name":"ip-10-0-143-61.ec2.internal","instance-id":"i-XXX","time":"2022-02-07T16:23:58Z","message":"Requesting instance drain"}
{"level":"info","time":"2022-02-07T16:23:58Z","message":"Error when trying to list Nodes w/ label, falling back to direct Get lookup of node"}
{"level":"error","error":"nodes \"XXX\" not found","time":"2022-02-07T16:23:58Z","message":"Unable to fetch node labels for node 'XXX' "}
{"level":"info","pod_names":[],"node_name":"XXX","time":"2022-02-07T16:23:58Z","message":"Pods on node"}
{"level":"info","time":"2022-02-07T16:23:58Z","message":"XXX"}
{"level":"error","error":"nodes \"XXX\" not found","time":"2022-02-07T16:23:58Z","message":"node 'XXX' not found in the cluster"}
```

**Environment**

* NTH App Version: 1.14.0
* NTH Mode (IMDS/Queue processor): QP
* OS/Arch: Linux, amd64
* Kubernetes version: 1.21
* Installation method: helm

**Comment by gabegorelick** [comment]
Relevant code: https://github.com/aws/aws-node-termination-handler/blob/d6d71c4cd0d44961f3138e3fad26582113c54c23/cmd/node-termination-handler.go#L339-L358

When a node doesn't belong to the cluster, `cordonAndDrainNode` and `cordonNode` naturally return an error. That means NTH doesn't run any post drain tasks, which makes since since we didn't drain. But a post drain task is where lifecycle hooks are completed. So by not running the post drain tasks, we're not completing the lifecycle hooks. https://github.com/aws/aws-node-termination-handler/blob/da8a26834419bd87fad2e7b73383184d2d5553a4/pkg/monitor/sqsevent/asg-lifecycle-event.go#L83-L90

In the event that a node has no pods/is not a member of this cluster, then you could argue that it's already been drained successfully (by not needing to drain at all), and thus you should run post drain tasks.

**Comment by snay2** [comment]
This if beyond the scope of what we expect NTH to be able to handle.

When NTH receives and event for an instance that is not part of the cluster, it does not know whether this is because the instance was intended to join the cluster but failed for an unknown reason, or whether the instance is running a customer workload in some other place (another cluster or standalone). As such, it would be dangerous for NTH to complete a lifecycle hook on an instance for which it does not have this information, because it could prematurely terminate a valid workload. In addition, the likely cause of such a failure is a misconfiguration of ASG, launch templates, SQS queues, or EventBridge rules. These configurations are outside the control of NTH, and by having NTH complete these lifecycle hooks anyway, we would be masking those failures and potentially making them harder to diagnose.
