### ISSUE TITLE
Error at making custom webhook template to send it to Microsoft teams

### ISSUE THREAD

**Issue by darkgordon** [aws/aws-node-termination-handler#578]
Hello!, I hope everything is going and doing well, Recently I am trying to make a custom templeate webhook to send it to microsoft Teams, the problem is that I dont know if I am doing right when writing my custom template and I get some the following error :(  

**Error**
values.yaml: error converting YAML to JSON: yaml: line 102: did not find expected key

**Steps to reproduce**

1. I create my custom template to send it like messager to microsoft Teams
`{
  "@type": "MessageCard",
  "summary": "Node Termination Handler",
  "themeColor": "FF00E8",
  "title": "Node Termination Handler Spot Interruption",
  "sections": [
    {
      "facts": [
        {
          "name": "Description:",
          "value": "{{ .Description }}"
        },
        {
          "name": "Node Name",
          "value": "{{ .NodeName }}"
        },
        {
            "name": "Instance ID",
            "value": "{{ .InstanceID }}"
        },
        {
          "name": "StartTime",
          "value": "{{ .StartTime }}"
        }

      ]
    }
  ]
}`

2. Then I parse my file to one line and get the following result:

`{"type":"MessageCard","summary":"Node Termination Handler","themeColor":"FF00E8","title":"Node Termination Handler Spot Interruption","sections":[{"facts":[{"name":"Description:","value":"{{ .Description }}"},{"name":"Node Name","value":"{{ .NodeName }}"},{"name":"Instance ID","value":"{{ .InstanceID }}"},{"name":"Autoscaling group","value":"{{ .AutoScalingGroupName }}"},{"name":"StartTime","value":"{{ .StartTime }}"}]}]}`

3. I added to my custom values.yaml (I am using helm chart version version: 0.15.3 and appVersion: 1.13.3)

webhookTemplate: "{"type":"MessageCard","summary":"Node Termination Handler","themeColor":"FF00E8","title":"Node Termination Handler Spot Interruption","sections":[{"facts":[{"name":"Description:","value":"{{ .Description }}"},{"name":"Node Name","value":"{{ .NodeName }}"},{"name":"Instance ID","value":"{{ .InstanceID }}"},{"name":"Autoscaling group","value":"{{ .AutoScalingGroupName }}"},{"name":"StartTime","value":"{{ .StartTime }}"}]}]}"

4. I tried to eliminate "type" but dont seems to work :(

**Expected outcome**
I expect to my custom webhooktemplate works

**Application Logs**
values.yaml: error converting YAML to JSON: yaml: line 102: did not find expected key

Thanks all for your help :)

**Comment by darkgordon** [comment]
Hello :), I fix the issue by deleting the double quotes and setting the template in this way

webhookTemplate: {"summary":"Node Termination Handler","themeColor":"FF00E8","title":"Node Termination Handler Spot Interruption","sections":[{"facts":[{"name":"Description:","value":"{{ .Description }}"},{"name":"Node Name","value":"{{ .NodeName }}"},{"name":"Instance ID","value":"{{ .InstanceID }}"},{"name":"StartTime","value":"{{ .StartTime }}"}]}]}

But I get a new error 
2022/02/09 14:58:06 WRN Webhook Error: Received Non-Successful Status Code status_code=400

Thats means I am sending bad values to the webhook, anyone has a microsoft template that I could use :)

Thanks

**Comment by jillmon** [comment]
Unfortunately, we don't have any experience working with Microsoft teams. Perhaps someone else in the community does?

**Comment by bwagner5** [comment]
Did you try using single quotes around the json in the values.yaml? 

Also, are you including the Bearer Token in the header? https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference?view=azure-bot-service-4.0#headers

Here's the config for webhook headers:
https://github.com/aws/aws-node-termination-handler/tree/main/config/helm/aws-node-termination-handler#:~:text=%22%22-,webhookHeaders,-Replace%20the%20default
