### ISSUE TITLE
Support autoscaling lifecycle hooks via the daemonset

### ISSUE THREAD

**Issue by tomelliff** [aws/aws-node-termination-handler#607]
**Describe the feature**
https://aws.amazon.com/about-aws/whats-new/2022/03/amazon-ec2-auto-scaling-lifecycle-instance-metadata/ announces that the IMDS now supports autoscaling lifecycle hooks so processes running on the EC2 instance are able to respond to the state of these without having to subscribe to EventBridge events.

**Is the feature request related to a problem?**
Safely draining a node is important for not disrupting workloads running in Kubernetes but the queue processor mode is more complex to set up than the daemonset mode and leads to this repo having multiple code paths. Supporting this feature in daemonset mode simplifies things for users but potentially allows the queue processor mode to be deprecated, simplfiying the code here too.

**Describe alternatives you've considered**
Just using the queue processor mode is fine but as mentioned above is more complex.

**Comment by tomelliff** [comment]
Hmmm... from reading https://docs.aws.amazon.com/autoscaling/ec2/userguide/retrieving-target-lifecycle-state-through-imds.html I don't think this gives you the token to be able to complete the lifecycle action so the lifecycle hook would have to be configured with a short timeout period to do the completion.

**Comment by jmauro** [comment]
This implementation would be awesome, any updates?
