### ISSUE TITLE
ServiceMonitor label selector is wrong

### ISSUE THREAD

**Issue by paalkr** [aws/aws-node-termination-handler#608]
**Describe the bug**
The ServiceMonitor object selector doesn't refer to the Service object, but to the Deployment object.

**Steps to reproduce**
Deploy nth in Queue Processor mode with `enablePrometheusServer: true` and `serviceMonitor.create: true`
The ServiceMonitor object will have the `spec.selector.matchLabels.app.kubernetes.io/component: deployment` set, hence no endpoints are picked up by Prometheus for scraping.

**Expected outcome**
The ServiceMonitor object should have `spec.selector.matchLabels.app.kubernetes.io/component:` set to {{ .Release.Name }}, wich is in fact the labels used by the service.

https://github.com/aws/aws-node-termination-handler/blob/85739d23b5e2c4184a092833e0619ecad2d9d215/config/helm/aws-node-termination-handler/templates/service.yaml#L7-L8

https://github.com/aws/aws-node-termination-handler/blob/85739d23b5e2c4184a092833e0619ecad2d9d215/config/helm/aws-node-termination-handler/templates/_helpers.tpl#L51

**Environment**
* NTH App Version: 1.16.0
* NTH Mode (IMDS/Queue processor): QP
* Installation method: Helm 0.18.0

**Comment by jillmon** [comment]
Also maybe https://github.com/aws/aws-node-termination-handler/pull/604
