### ISSUE TITLE
Emit pod events on node drain 

### ISSUE THREAD

**Issue by dennisme** [aws/aws-node-termination-handler#635]
**Describe the feature**
A concise description of the feature and desired behavior.

On node drain the pods running on said node should emit events. These events can then be used to monitor at the pod level.  Without this you have to know which nodes a specific pod was running on then snag the node events. This feature would prevent that recursive lookup.

**Comment by jillmon** [comment]
@dennisme, are you still working on this issue? The PR you posted was recently closed for inactivity. If you are still interested in making the change please reopen.

**Comment by snay2** [comment]
Released in NTH `v1.18.0` (Helm chart version `v0.20.0`).
