### ISSUE TITLE
get a shell to a running termination-handler container

### ISSUE THREAD

**Issue by ythabti** [aws/aws-node-termination-handler#639]
**Describe the bug**
I am trying to get a shell to a running termination-handler container

**Steps to reproduce**
run : kubectl exec -i -t -n kube-system aws-termination-handler-66hpp -c aws-termination-handler -- sh -c "clear; (bash || ash || sh)"

**Expected outcome**
get a shell to the running termination-handler container or run commands on the running container 

**Application Logs**
error: Internal error occurred: error executing command in container: failed to exec in container: failed to start exec "d44cfclksjqdfjlmsjzerz231sfd654ze32165f1zd": OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "/bin/bash": executable file not found in $PATH: unknown

**Environment**

* NTH App Version:
* NTH Mode (IMDS/Queue processor): 
* OS/Arch:
* Kubernetes version: 1.21.9
* Installation method: [all-resources.yaml](https://github.com/aws/aws-node-termination-handler/releases/download/v1.16.3/all-resources.yaml)

**Comment by cjerad** [comment]
Hi ythabti,

The container image does not contain a shell.  The [Dockerfile](https://github.com/aws/aws-node-termination-handler/blob/52228f5ae5ba32cc479ad5ea339ca978a8560524/Dockerfile#L27-L29) builds the image from [scratch](https://hub.docker.com/_/scratch).

Why do you need a shell?  If it is so you can inspect the logs then you can use `kubectl logs` to target the specific container.
