### ISSUE TITLE
Include EventID in metrics

### ISSUE THREAD

**Issue by cmotta2016** [aws/aws-node-termination-handler#650]
**Describe the feature**
We're running NTH to handler AZ Rebalance recommendation and Spot interruption notification. We need to build a Grafana dashboard to show only the number of instances terminated by Spot interruption. So if there is a label like `event-id=spot-itn-event...` we can filter the query by this label.

**Is the feature request related to a problem?**
When using Grafana/Prometheus we can't filter instances terminated by a specific event.

**Describe alternatives you've considered**
/

**Comment by mohitreddy1996** [comment]
Thanks a lot @cmotta2016 and @snay2 for merging this change in. 

Would it be possible to make a release for with this change? 

I see that the docker image - https://hub.docker.com/r/amazon/aws-node-termination-handler/tags, was updated ~5 months ago?

**Comment by snay2** [comment]
@mohitreddy1996 You're correct, our most recent release was 2 months ago in May, [`v1.16.5`](https://github.com/aws/aws-node-termination-handler/releases/tag/v1.16.5). We're planning to cut another release early next week once we get the fix for #654 merged. I'll update this issue once that happens.

**Comment by mohitreddy1996** [comment]
Awesome! Thanks a bunch :)

**Comment by mohitreddy1996** [comment]
Hi @snay2 , quickly wanted to check on the progress of cutting a new release. Any ETAs? Thanks in advance :)

**Comment by snay2** [comment]
Thanks for checking in! The fix is nearly ready: https://github.com/aws/aws-node-termination-handler/pull/669, with a couple last-minute adjustments to make. I expect we'll release in the next day or two.

**Comment by snay2** [comment]
This has finally been released! NTH app version [`v1.17.0`](https://github.com/aws/aws-node-termination-handler/releases/tag/v1.17.0). Helm chart version [`v0.19.0`](https://github.com/aws/eks-charts/releases/tag/v0.0.100).
