### ISSUE TITLE
some IMDS debug logs appear while in queue-processor mode

### ISSUE THREAD

**Issue by icelynjennings** [aws/aws-node-termination-handler#655]
**Describe the bug**

DEBUG messages such as `Trying to get token from IMDSv2` appear in NTH in queue processor mode.

**Steps to reproduce**

Run NTH in `Queue processor` mode with loglevel `DEBUG`.

**Expected outcome**

IMDSv2 logs do not appear in Queue processor mode
Connections related to IMDSv2 are not made to the EC2 instance's metadata internal endpoint

**Application Logs**

```
Trying to get token from IMDSv2
Unable to retrieve an IMDSv2 token, continuing with IMDSv1, Put "http://169.254.169.254/latest/api/token": context deadline exceeded 
```

**Environment**

* NTH App Version: chart 0.18.5 via https://artifacthub.io/packages/helm/aws/aws-node-termination-handler
* NTH Mode (IMDS/Queue processor): Queue processor
* OS/Arch: bottlerocket 
* Kubernetes version: EKS 1.21.6
* Installation method: EKS / Helm chart

**Comment by AustinSiu** [comment]
Hi @icelynjennings! When NTH runs in Queue-Processor mode, it will still use the Instance Metadata Service to access information that is relevant in both IMDS mode and QP mode. In particular, we use IMDS to get the AWS region when it isn't explicitly provided by the user: https://github.com/aws/aws-node-termination-handler/blob/47b54fa44a9dad214ef3d5fb8ba9a186083c2b8a/cmd/node-termination-handler.go#L108-L111 

So these logs are expected when running NTH, regardless of operating mode.
