### ISSUE TITLE
helm: add envFrom templating option

### ISSUE THREAD

**Issue by cesarmira** [aws/aws-node-termination-handler#662]
**Describe the feature**
I would like to be able to configure the DaemonSet envFrom values from the values.yaml

**Is the feature request related to a problem?**
No, as right now we can't configure it at all.

**Describe alternatives you've considered**
At the moment, we are rendering the chart, updating the manifest and applying it manually. We believe it would be nice to be able to do it everything from the chart.

**Comment by snay2** [comment]
Thanks for the suggestion! We'd be happy to accept a pull request with a fix for this issue.

Along with that, we'll help write an end-to-end test that verifies that the environment variables successfully appear in the pod after launch.
