### ISSUE TITLE
Support instance ID hostnames

### ISSUE THREAD

**Issue by bwagner5** [aws/aws-node-termination-handler#666]
**Describe the feature**
A concise description of the feature and desired behavior.

Instances can now have hostnames that are the instance id rather than the IP address of an instance. The hostname maps to the kubernetes node name. NTH should support instance id node names.

**Is the feature request related to a problem?**
A description of what the problem is. For example: I'm frustrated when [...]

Termination handling does not work properly when the inferred node name is incorrect. 

**Describe alternatives you've considered**
A description of any alternative solutions or features you've considered.

N/A

**Comment by k4kratik** [comment]
up
