### ISSUE TITLE
Node Termination Handler only logs to stderr

### ISSUE THREAD

**Issue by vbyrd** [aws/aws-node-termination-handler#667]
**Describe the bug**
NTH only logs to stderr

See this line of code for the culprit:
https://github.com/aws/aws-node-termination-handler/blob/70eab8817e3b16482d58ae9a12f5bdb505ca5970/cmd/node-termination-handler.go#L59

**Steps to reproduce**
View log output of the NTH with stderr redirector to /dev/null

**Expected outcome**
NTH logs to stdout for normal events and stderr for actual error events.

**Application Logs**
<img width="867" alt="aws-node-termination-handler-logs" src="https://user-images.githubusercontent.com/619450/183145333-0de36ef7-7554-4491-8847-81fa01121461.png">

**Environment**

* NTH App Version:  v1.16.5
* NTH Mode (IMDS/Queue processor): QP
* OS/Arch: linux
* Kubernetes version:  1.22
* Installation method: Helm

**Comment by snay2** [comment]
This has been released in `v1.17.1`, chart version `0.19.1`
