### ISSUE TITLE
Create Helm Chart

### ISSUE THREAD

**Issue by RobertoUa** [aws/aws-node-termination-handler#7]

**Comment by mattrandallbecker** [comment]
We'll work on adding this, thank you for the suggestion.

**Comment by andysnowden** [comment]
IMO the chart should be created here https://github.com/helm/charts with a linkback.  Would be happy to help draft a initial version and submit if that's ok.

**Comment by max-rocket-internet** [comment]
Here might be better: https://github.com/aws/eks-charts

I think AWS are moving towards this repo. It makes sense as getting new charts committed to the stable main Helm repo, and the PR process, can be quite painful.

**Comment by max-rocket-internet** [comment]
To quote the Helm 3 release yesterday:

> This change reflects a philosophical shift in Helm. We no longer attempt to maintain an official stable charts repository. The ecosystem is just too big, and the task proved overwhelming even for a dedicated group of maintainers

**Comment by jillmon** [comment]
Hello, the helm chart that corresponds to this project has been created and added to the eks repository. It can be found here https://github.com/aws/eks-charts/tree/master/stable/aws-node-termination-handler.
