### ISSUE TITLE
No SQS retry on "read: connection reset by peer"

### ISSUE THREAD

**Issue by eugenea** [aws/aws-node-termination-handler#717]
**Describe the bug**
NTH does not retry request over AWS SDK API to retrieve SQS queue message.

**Steps to reproduce**
Close firewall to SQS AWS endpoint and try to monitor for SQS events.

**Expected outcome**
The network layer cannot be guaranteed to be reliable so need to implement retry logic here.

**Application Logs**
```
WRN There was a problem monitoring for events error="RequestError: send request failed\ncaused by: Post \"https://sqs.us-west-2.amazonaws.com/\": read tcp 100.100.xx.xx:xxxx->10.xx.xx.xx:443: read: connection reset by peer" event_type=SQS_TERMINATE
```

**Environment**

* NTH App Version: v1.16.3
* NTH Mode (IMDS/Queue processor): Queue processor 
* OS/Arch: Linux
* Kubernetes version: v1.21.14-eks 
* Installation method: deployment

The check that denies retry is [here](https://github.com/aws/aws-sdk-go/blob/main/aws/request/connection_reset_error.go)
For V1 of AWS SDK the fix should be custom retryer which re-implements [should retry](https://github.com/aws/aws-sdk-go/blob/e2d6cb448883e4f4fcc5246650f89bde349041ec/aws/client/default_retryer.go#L131), and custom retryer should be injected [here](https://github.com/aws/aws-node-termination-handler/blob/main/cmd/node-termination-handler.go#L189),  however upgrade to V2 of AWS SKD should fix this issue automatically,  because it does not make distinction between different kinds of [connection reset](https://github.com/aws/aws-sdk-go-v2/blob/b7d8e15425d2f86a0596e8d7db2e33bf382a21dd/aws/retry/retryable_error.go#L103) and retries them all which is desired behavior here.

**Comment by snay2** [comment]
Thank you for the suggestion! Upon first reading, we would favor doing the upgrade to v2 of the AWS SDK if it can handle this logic automatically.

**Comment by eugenea** [comment]
Do you have any timeline/plan for v2 upgrade?

**Comment by jillmon** [comment]
@eugenea, the [beta version](https://github.com/aws/aws-node-termination-handler/tree/v2) of the NTH v2 upgrade has recently been released. Have you had a chance to investigate whether then new SDK can handle this use case?

**Comment by tiationg-kho** [comment]
Added a custom retryer for SQS in NTH v1. Please let us know if there is any other issue. Thank you!

**Comment by tiationg-kho** [comment]
We have released new version that will handle this issue. Appreciate for finding the issue
https://github.com/aws/aws-node-termination-handler/releases/tag/v1.23.1
