### ISSUE TITLE
Update e2e K8s test version matrix

### ISSUE THREAD

**Issue by bwagner5** [aws/aws-node-termination-handler#727]
**Describe the feature**
A concise description of the feature and desired behavior.

K8s 1.24 was released for EKS and kOps already support 1.25. 

The e2e K8s version matrix can be updated to K8s 1.21, 1.22, 1.23, 1.24, and 1.25. 

K8s 1.18-1.20 is now EOL in EKS and has been EOLd upstream for quite a while. https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html

**Is the feature request related to a problem?**
A description of what the problem is. For example: I'm frustrated when [...]

**Describe alternatives you've considered**
A description of any alternative solutions or features you've considered.

**Comment by snay2** [comment]
Agreed. We're planning to make this change once the PSP deprecation is complete, to enable support for 1.25. Tracking that work here: #638
