### ISSUE TITLE
Declare scheduled event draining as stable

### ISSUE THREAD

**Issue by johngmyers** [aws/aws-node-termination-handler#738]
**Describe the feature**

Scheduled event draining has been marked  in the Helm chart values.yaml as [EXPERIMENTAL] for almost three years now. That's a long time to run an experiment. Has there not been enough experience with the feature to declare it stable?

**Is the feature request related to a problem?**

I would like to have kOps enable this feature by default, but won't enable an experimental feature by default.

**Describe alternatives you've considered**

Leave it disabled by default.

**Comment by snay2** [comment]
Good catch! It's safe to declare this feature stable now. Feel free to submit a PR to that effect; otherwise we will pick it up when we have time.

**Comment by cjerad** [comment]
Included in release v1.18.2
