### ISSUE TITLE
Document queue mode single- and multi-replica behavior

### ISSUE THREAD

**Issue by jasonstitt** [aws/aws-node-termination-handler#775]
**Describe the feature**

I've read the comment for NTH deployment replica count:

> The number of replicas in the NTH deployment when using queue-processor mode (NOTE: increasing this may cause duplicate webhooks since NTH pods are stateless)

Without additional knowledge on the internal workings, this comment is difficult to interpret. It would be helpful to have documentation in the README of the implications of both single and multi replica deployments.

For example (these are made up - I'm guessing all of them, which is why I'd appreciate docs):
* With a single replica, the draining of other nodes could be delayed if the node NTH is on is the first one terminated (?)
* With multiple replicas, draining might take more than the 30s default visibilityTimeout of an SQS queue and therefore the messages might be picked up by another replica (?)
* visibilityTimeout could be increased with XXX other implications (?)

**Comment by stevehipwell** [comment]
This is related to https://github.com/aws/aws-node-termination-handler/issues/718.
