### ISSUE TITLE
Nodes are cordoned and drained when a rebalance recommendation is received even when configured not to

### ISSUE THREAD

**Issue by danports** [aws/aws-node-termination-handler#786]
**Describe the bug**
NTH cordons and drains nodes for which a rebalance recommendation is received even when it is configured not to.

**Steps to reproduce**
1. Run NTH in queue processor mode with the `ENABLE_REBALANCE_MONITORING` and `ENABLE_REBALANCE_DRAINING` environment variables both set to `false`.
2. Wait for AWS to send a node rebalance recommendation.
3. NTH cordons and drains the node.

**Expected outcome**
NTH shouldn't cordon and drain the node.

**Application Logs**
NTH logs its configuration on startup, which confirms that the relevant variables have been set correctly:
```{"level":"info","dry_run":false,"node_name":"i-xxx","pod_name":"aws-node-termination-handler-5cb6f68945-bvpcm","metadata_url":"http://169.254.169.254","kubernetes_service_host":"100.64.0.1","kubernetes_service_port":"443","delete_local_data":true,"ignore_daemon_sets":true,"pod_termination_grace_period":-1,"node_termination_grace_period":120,"enable_scheduled_event_draining":false,"enable_spot_interruption_draining":false,"enable_sqs_termination_draining":true,"enable_rebalance_monitoring":false,"enable_rebalance_draining":false,"metadata_tries":3,"cordon_only":false,"taint_node":false,"taint_effect":"NoSchedule","exclude_from_load_balancers":true,"json_logging":true,"log_level":"info","webhook_proxy":"","uptime_from_file":"","enable_prometheus_server":false,"prometheus_server_port":9092,"emit_kubernetes_events":true,"kubernetes_events_extra_annotations":"","aws_region":"us-east-1","aws_endpoint":"","queue_url":"https://sqs.us-east-1.amazonaws.com/xxx","check_tag_before_draining":true,"ManagedTag":"aws-node-termination-handler/managed","use_provider_id":true,"time":"2023-03-02T09:17:05Z","message":"aws-node-termination-handler arguments"}```

**Environment**

* NTH App Version: 1.17.1
* NTH Mode (IMDS/Queue processor): Queue processor
* OS/Arch: Docker image
* Kubernetes version: 1.25.7
* Installation method: kOps add-on

**Comment by cjerad** [comment]
Hi @danports, Queue Processor does not use the `enableRebalanceMonitoring` and `enableRebalanceDraining` Helm chart values.  IMDS mode does use those values.

**Comment by danports** [comment]
So to clarify, there is no way to configure or disable NTH's behavior when a rebalance recommendation is received in queue processor mode, right? I worked around this by disabling the EventBridge rule that kOps automatically created to send rebalance recommendation events to the queue, so it's not a big deal in my use case.

**Comment by cjerad** [comment]
There is the `cordonOnly` Helm value, but that will apply when handling all event types.

**Comment by danports** [comment]
I'm not using the Helm chart to deploy NTH - kOps configures NTH via environment variables on the pod/deployment.

**Comment by cjerad** [comment]
Setting the `CORDON_ONLY` environment variable to "true" will have the same effect.

**Comment by bdbrink** [comment]
This was an issue for me as well, we have apps that run high amounts of CPU at startup that we don't want to scale down once they start. AWS recommends them to be rebalanced so it left around 17 nodes cordoned. Just removed the rebalance events from the sqs stack and it solved that.

**Comment by jan-ludvik** [comment]
We also are receiving many rebalance recommendation in Queue processor in us-east-1 during US business hours start. Can this be fixed so we can properly turn this off?
Removing the infrastructure for this event works I guess but it's not really clean.
