### ISSUE TITLE
Support windows spot instances

### ISSUE THREAD

**Issue by rparsonsbb** [aws/aws-node-termination-handler#8]
Looks like the current daemonset and image is only for linux, is there a plan on the roadmap to support windows spot instances or should a pull request be made?

**Comment by mattrandallbecker** [comment]
We'll definitely investigate windows support.  We'll do some testing and get back to you.

**Comment by doryanmzr** [comment]
any update on that?

**Comment by mattrandallbecker** [comment]
Sorry for the delay, we got closer to supporting windows with our manifest builds for docker images but we still need to prioritize the build and release script changes to make this happen then perform some testing to ensure it works.

**Comment by doryanmzr** [comment]
> Sorry for the delay, we got closer to supporting windows with our manifest builds for docker images but we still need to prioritize the build and release script changes to make this happen then perform some testing to ensure it works.

I'd like to know if there is any progress :)

**Comment by cjerad** [comment]
> I'd like to know if there is any progress

I'm working on this now

**Comment by cshivashankar** [comment]
Hi, Any idea when this might be released. I am trying to get an approximate time frame so that I can plan accordingly.

**Comment by jillmon** [comment]
@cjerad is currently in the process of scoping the requirements for this change. We should be able to give you a better estimate of completion within another week or so. Since this is such a new feature, we want to make sure that it is adequately reviewed and tested, but this feature is now on our official roadmap. We expect to complete it soon.

**Comment by cshivashankar** [comment]
Hi @jillmon Many thanks for the update. I will be following this thread for more info

**Comment by bwagner5** [comment]
Windows support was released a while back, thanks to @cjerad!  🥳🎊🚀🤩

We would love to hear feedback from anyone using NTH on windows!  I'm going to close this issue, but feel free to comment here on your experience or open a new issue.
