### ISSUE TITLE
`actions_node` metric not changing again

### ISSUE THREAD

**Issue by ktreptow** [aws/aws-node-termination-handler#824]
We want to get notified based on the `actions_node` when a node gets cordoned and drained. For this we currently use Prometheus Alerts. We noticed, that a metric doesn't get reset to 0 again, even if the node in question doesn't exist anymore. This makes it really difficult to tell which alerts are actually currently firing and which ones are just "leftovers" from previous metrics.

Would it be possible to reset the metrics again or change the state after successful draining and cordoning? We also wonder how the metrics behave when a node gets cordoned _twice_ with some time in between. Would the metric even change for the second occurence or just stay active? 

Thank you!

**Comment by bwagner5** [comment]
There is a "post-drain" state that happens after the "cordon-and-drain" state.  If two cordons occur, metrics should be incremented to signify two cordons have occurred.
