### ISSUE TITLE
Misleading output when the pods are evicted

### ISSUE THREAD

**Issue by r-aju** [aws/aws-node-termination-handler#841]
**Describe the bug**
We have AWS Node Termination Handler deployed on EKS Cluster which is running in IMDS Mode, the application runs as a daemonset across all the nodes in the cluster. On the output of the pod we see that the termination handler showing that the pods are evicted, but with the standard `stderr` which depicts that the application didn't drain the nodes or has it drained the node but the status code being misleading.

**Steps to reproduce**
Deploying the node termination handler on EKS Cluster

**Expected outcome**
not throwing `stderr` output when the Node termination Handler when it drains the pods on the node.

**Application Logs**
```
2023-06-19 11:36:37	
2023-06-19T06:06:37.328080017Z `stderr` F 2023/06/19 06:06:37 ??? evicting pod <name>
2023-06-19 11:36:37	
2023-06-19T06:06:37.328077317Z `stderr` F 2023/06/19 06:06:37 ??? evicting pod <name>
2023-06-19 11:36:37	
2023-06-19T06:06:37.328066343Z `stderr` F 2023/06/19 06:06:37 ??? evicting pod <name>
2023-06-19 11:36:37	
2023-06-19T06:06:37.328036693Z `stderr` F 2023/06/19 06:06:37 ??? evicting pod <name>
```

**Environment**

* NTH App Version: v1.19.0
* NTH Mode (IMDS/Queue processor): IMDS
* OS/Arch: Amazon Linux
* Kubernetes version: v:1.24
* Installation method: helm
```
helm upgrade --install aws-node-termination-handler \
--namespace kube-system \
--set enableSpotInterruptionDraining="true" \
--set enableScheduledEventDraining="true" \
--set enableRebalanceMonitoring="true" \
--set enableRebalanceDraining="true" \
--set webhookURL=<webhook URL> \
eks/aws-node-termination-handler
```

**Comment by pete911** [comment]
Hi @r-aju, the actual log line comes from drain helper in k8s.io package. The helper allows out and errOut. Both are set in the Node package to `log.Logger`, which is basically zerolog. Zerolog by default writes to stderr. There is an opinion on what should be written to stdout and to stderr. Basically stdout should be used for application output and diagnostics issued by the program (logs) - https://www.gnu.org/software/libc/manual/html_node/Standard-Streams.html
I am not the maintainer, so I will let them decide (there is option in the helper to do what you want in a very simple way), but the question is if it is the right thing to do.

**Comment by GavinBurris42** [comment]
Hi @r-aju. As explained by @pete911, the drain helper's out and errOut are both set to the Zerolog default, which writes to Stderr. The log you mentioned is through the out log, informing that the pods were successfully evicted in the draining process. Was your question whether the draining was successful, or were you requesting that the log should be written to Stdout?

**Comment by r-aju** [comment]
@GavinBurris42 , Yes that was my concern.
