### ISSUE TITLE
EC2 IMDS requests made with all configuration provided

### ISSUE THREAD

**Issue by kgtw** [aws/aws-node-termination-handler#855]
**Describe the bug**

When NTH is configured with SQS/IMDS termination draining, the code makes API calls to EC2 IMDS when all of the required configuration is provided within the specified `QUEUE_URL` env var.

This is problematic for cluster operators that are trying to implement network policies. As the dropped traffic for EC2 IMDS can result in false-positives within the reported metrics of dropped traffic.

Problem line(s): https://github.com/aws/aws-node-termination-handler/blob/ba95e6d6d8c43451f3c8e952ff570404410519cc/cmd/node-termination-handler.go#L123
https://github.com/aws/aws-node-termination-handler/blob/ba95e6d6d8c43451f3c8e952ff570404410519cc/cmd/node-termination-handler.go#L128-L134
**Steps to reproduce**

Configure NTH with `ENABLE_SQS_TERMINATION_DRAINING="true"` and `QUEUE_URL=https://sqs.eu-central-1.amazonaws.com/xxxxx`

**Expected outcome**

NTH to not make any API calls to EC2 IMDS

**Application Logs**
The log output when experiencing the issue.

**Environment**

* NTH App Version: v1.19.0
* NTH Mode (IMDS/Queue processor): SQS / IMDS
* OS/Arch: ubuntu
* Kubernetes version: 1.24.13
* Installation method: helm

**Comment by cjerad** [comment]
Hi @kgtw! Just checking that I understand the issue correctly: you are seeing requests to IMDS when running in Queue Processor (QP) mode.  Correct?

When QP mode is enabled the IMDS client is not even initialized.

https://github.com/aws/aws-node-termination-handler/blob/57b3a3dc8651155522e5c0b5781c2bad3e2091d4/cmd/node-termination-handler.go#L116
https://github.com/aws/aws-node-termination-handler/blob/57b3a3dc8651155522e5c0b5781c2bad3e2091d4/cmd/node-termination-handler.go#L122-L123

Is it possible that NTH has been deployed twice? One in QP mode, the other in IMDS mode.

**Comment by kgtw** [comment]
Hi @cjerad 

We are running only a single instance of NTH in SQS/IMDS mode. As mentioned in my original message, we have provided all of the appropriate configuration via environment variables so that NTH shouldn't need to talk to IMDS. Even with the configuration provided, NTH still makes API calls to IMDS which is used to determine the region, something we have already provided via environment variables.

From a security perspective, this is more ideal for us as it means that services cannot retrieve the instance document policy _(and subsequent instance role permissions)_ via IMDS and we can enforce strict egress network policies.
- https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html#instance-metadata-security-credentials

**Comment by kgtw** [comment]
Ah actually ignore this. I just noticed I reported this when looking at latest/master code where we are still running v1.14.0 in our clusters which does face the problem I reported but has since been fixed.

https://github.com/aws/aws-node-termination-handler/blob/v1.14.0/cmd/node-termination-handler.go#L108C40-L108C40
