### ISSUE TITLE
Allow short name matching

### ISSUE THREAD

**Issue by dcarrion87** [aws/aws-node-termination-handler#857]
Using SQS Mode when the event comes in it's checking against the FQDN only:

E.g.

```
2023/06/28 05:10:57 WRN Unable to list Nodes w/ label, falling back to direct Get lookup of node
2023/06/28 05:10:57 ERR Unable to fetch node labels for node 'ip-10-X-X-X.ap-southeast-2.compute.internal'  error="nodes \"ip-10-X-X-X.ap-southeast-2.compute.internal\" not found"
```

But the `kubernetes.io/hostname` assigned by K3s servers is the short name as we're running on Ubuntu. E.g. just `ip-10-X-X-X`.

Don't see any way to instruct the node termination handler to do a short name match. Any ideas and/or thoughts welcomed.

At this stage I have overriden host to fqdn.

**Comment by ssoriche** [comment]
We're experiencing the same issue with kubernetes 1.24 running under kOps. The node names are now the instance IDs, and node termination handler is trying to apply the taint by the hostname, not the node name.

When looking through the logs, anywhere else `node_name` is mentioned, the value is correct, the taint application log line is:
