### ISSUE TITLE
Helm chart 0.22.0 not on eks-charts repo

### ISSUE THREAD

**Issue by alantang888** [aws/aws-node-termination-handler#892]
**Describe the bug**
Helm chart 0.22.0 not on eks-charts

**Steps to reproduce**
Execute `helm repo add eks https://aws.github.io/eks-charts; helm repo update; helm search repo aws-node-termination-handler --versions` version 0.22.0 not found.

**Expected outcome**
Helm chart repo contain chart version `0.22.0`

**Application Logs**
Output of `helm search repo aws-node-termination-handler --versions`
```
$ helm search repo aws-node-termination-handler --versions
NAME                              	CHART VERSION	APP VERSION	DESCRIPTION
eks/aws-node-termination-handler  	0.21.0       	1.19.0     	A Helm chart for the AWS Node Termination Handler.
eks/aws-node-termination-handler  	0.20.3       	1.18.3     	A Helm chart for the AWS Node Termination Handler.
eks/aws-node-termination-handler  	0.20.2       	1.18.2     	A Helm chart for the AWS Node Termination Handler.
eks/aws-node-termination-handler  	0.20.1       	1.18.1     	A Helm chart for the AWS Node Termination Handler.
eks/aws-node-termination-handler  	0.20.0       	1.18.0     	A Helm chart for the AWS Node Termination Handler.
...
```

**Comment by James-Johnson-SD** [comment]
Appears that's because https://github.com/aws/aws-node-termination-handler/pull/803  in v1.20.0 they moved from eks-charts to 
oci://public.ecr.aws/aws-ec2/helm/aws-node-termination-handler

**Comment by alantang888** [comment]
Thanks.
