### ISSUE TITLE
AWS Node Termination Handler Not Deleted after the Instance group deletes

### ISSUE THREAD

**Issue by sakmalh** [aws/aws-node-termination-handler#893]
**Describe the bug**
I am using KOPs. I have three Master Nodes in each AZs. I deleted one of the Instance group of an AZ because it was not ready yet to join the cluster and was causing issue. This pod kube-system/aws-node-termination-handle was on pending and was not assigned a Node because one of the Node was not joining the cluster. 

**Expected outcome**
When I run kops validate cluster I get this error 
```
Pod	kube-system/aws-node-termination-handler-85667c79b4-8czs8	system-cluster-critical pod "aws-node-termination-handler-85667c79b4-8czs8" is pending
```

**Application Logs**
```
Name:                 aws-node-termination-handler-85667c79b4-lgvpg
Namespace:            kube-system
Priority:             2000000000
Priority Class Name:  system-cluster-critical
Service Account:      aws-node-termination-handler
Node:                 <none>

  Type     Reason            Age                From               Message
  ----     ------            ----               ----               -------
  Warning  FailedScheduling  68s (x4 over 16m)  default-scheduler  0/5 nodes are available: 2 node(s) didn't have free ports for the requested pod ports, 3 node(s) didn't match Pod's node affinity/selector. preemption: 0/5 nodes are available: 2 node(s) didn't have free ports for the requested pod ports, 3 Preemption is not helpful for scheduling.

```

**Environment**

* NTH App Version:
* NTH Mode (IMDS/Queue processor): 
* OS/Arch:
* Kubernetes version: 1.25.5
* Installation method: KOPs

**Comment by cjerad** [comment]
Hi sakmalh! Are you asking why the NTH Deployment was not removed when the instance group on which it was running was deleted?

**Comment by sakmalh** [comment]
Yeah you can close this. A node was not getting connected to the cluster due to etcd version. When I fixed this everything is fine. 

Thanks
