### ISSUE TITLE
Prometheus metric actions_node_total label node_event_id

### ISSUE THREAD

**Issue by azisi** [aws/aws-node-termination-handler#895]
**Describe the feature**
nth exposes the prometheus metric nth exposes the prometheus metric actions_node_total which has the label node_event_id. This label is essential a different value for each event. This is high cardinality level and will lead to an unbounded amount of increasing data, causing problems to both the scraping and prometheus.

Quote from https://prometheus.io/docs/practices/naming/

> CAUTION: Remember that every unique combination of key-value label pairs represents a new time series, which can dramatically increase the amount of data stored. Do not use labels to store dimensions with high cardinality (many different label values), such as user IDs, email addresses, or other unbounded sets of values.
 which has the label node_event_id. This label is essential a different value for each event. This is high cardinality level and will lead to an unbounded amount of increasing data, causing problems to both the scraping and prometheus.

Quote from https://prometheus.io/docs/practices/naming/

> CAUTION: Remember that every unique combination of key-value label pairs represents a new time series, which can dramatically increase the amount of data stored. Do not use labels to store dimensions with high cardinality (many different label values), such as user IDs, email addresses, or other unbounded sets of values.

**Is the feature request related to a problem?**
The current situation is causing scraping to timeout due to the amount of the time-series and increasing the disk size of prometheus 

**Describe alternatives you've considered**
Remove the label node_event_id

**Comment by iuriaranda** [comment]
We've been hitting this issue as well on most of our largest clusters. If the NTH Pods live for long enough, they can easily reach the default sample limit of 5000. IMO since this is very well documented as an anti-pattern for Prometheus, it should be labeled as a bug and be tackled rather sooner than later.

**Comment by corford** [comment]
We're also seeing this (temporary workaround is using the [descheduler](https://github.com/kubernetes-sigs/descheduler) to set a [Pod lifetime policy](https://github.com/kubernetes-sigs/descheduler/blob/master/docs/deprecated/v1alpha1.md#podlifetime) that restarts NTH periodically, clearing the samples)
