### ISSUE TITLE
AWS Node Termination Handler Support Policy 

### ISSUE THREAD

**Issue by shazib-summar** [aws/aws-node-termination-handler#896]
Hello just had a question regarding the currently supported versions of AWS Node Termination Handler for production envs. I went through the docs and couldnt find anything related to the support policy.

Thanks ❤️

**Comment by vineeth-bandi** [comment]
Hi, the latest release version is suitable for production environments. If your concern is over compatibility with different versions of Kubernetes that information is in this [table](https://github.com/aws/aws-node-termination-handler/blob/main/README.md#kubernetes-compatibility).

**Comment by shazib-summar** [comment]
Thanks for responding @vineeth-bandi I was actually looking to know the support policy i.e. which versions are supported/maintained at a given time. Say a bug fix is pushed will it be backported to previous releases etc.

**Comment by vineeth-bandi** [comment]
Bug fixes and updates are not backported, so the most recent release is recommended. [Release notes](https://github.com/aws/aws-node-termination-handler/releases) will indicate which fixes are applied to future versions.

**Comment by shazib-summar** [comment]
Thanks for the reply. Does release here mean major.minor or major.minor.patch?

**Comment by vineeth-bandi** [comment]
By release I mean those included [here](https://github.com/aws/aws-node-termination-handler/releases). So yes, it includes the patch version changes as well.

**Comment by shazib-summar** [comment]
Hey @vineeth-bandi, should this information be present in the docs or the readme? This could be helpful to a lot of users. I
l'll be more than happy to make a PR
