### ISSUE TITLE
How does this compare to the similar kube-aws project?

### ISSUE THREAD

**Issue by dharmab** [aws/aws-node-termination-handler#9]
We're currently using https://github.com/kube-aws/kube-spot-termination-notice-handler. What are the differences between this project and that one? Are there reasons to use one over the other, either for techincal or community reasons?

**Comment by mattrandallbecker** [comment]
I would say they are very similar in purpose.

The other project has more configuration options and the ability to send notifications.

In our project we intentionally wanted to avoid taking a dependency on kubectl and provide a small container footprint, as a result our implementation ended up being quite different.

I'd encourage you to use the one that best meets the needs of your organization.

**Comment by msusta** [comment]
@mattrandallbecker I'd maybe recommend putting a note about the difference / reasoning for a new project somewhere on the front page or in the FAQ. This was exactly my first question when I saw the announcement.

From what I have seen there are following projects:
- https://github.com/kube-aws/kube-spot-termination-notice-handler
- https://github.com/pusher/k8s-spot-termination-handler

**Comment by mattrandallbecker** [comment]
Thank you for the comment.  I'll see if I can put together a statement that outlines our motivations and add it to the readme.  In the meantime I'll try to share a bit more here.

We received feedback from our customers they had hesitation using an "unofficial" spot handler, and some of the other projects would not meet our requirements that they work with both self-managed Kubernetes and EKS.  We intend to support and add features to this project over the long term, but I'd still encourage customers to use whichever tooling works best for them even if it is not this project.
