### ISSUE TITLE
Update supported Kubernetes versions

### ISSUE THREAD

**Issue by morganrowse** [aws/aws-node-termination-handler#908]
Hi There,

We are currently running recent versions of Kubernetes, 1.28, 1.27 etc. and would like to make use of AWS NTH. However the README doesn't show if these versions are supported. Please advise if NTH supports newer versions of Kubernetes.

**Comment by rr-krupesh-savaliya** [comment]
Same problem

**Comment by aleonsan** [comment]
+1

**Comment by noamgreen** [comment]
+1
