### ISSUE TITLE
More DrainEvent metadata to potentially use in the webhook template

### ISSUE THREAD

**Issue by tbarrella** [aws/aws-node-termination-handler#94]
Hello, thank you for open sourcing this, it seems to be working well!

I noticed that the webhook template allows you to use fields from the associated DrainEvent. It would be helpful if more fields were available, like node name, instance type, and potentially instance id. It seems like these could all come from the Node object

**Comment by bwagner5** [comment]
Thanks for requesting this feature! I agree that it would be useful to add more context for the webhooks. We'll look into adding this functionality!

**Comment by bwagner5** [comment]
added additional node metadata for webhooks and released in v1.3.0
