### ISSUE TITLE
can't install any helm chart following the instructions in the readme

### ISSUE THREAD

**Issue by satra** [aws/aws-node-termination-handler#958]
**Describe the bug**
can't install the handler in a k8s 1.28 system

**Steps to reproduce**

follow the readme.

**Expected outcome**
an issue #954 is open for 1.21.0 but the same holds for 1.20.0

**Application Logs**
```
$ helm upgrade --install aws-node-termination-handler           --namespace kube-system           oci://public.ecr.aws/aws-ec2/helm/aws-node-termination-handler --version v1.20.0
Release "aws-node-termination-handler" does not exist. Installing it now.
Error: public.ecr.aws/aws-ec2/helm/aws-node-termination-handler:v1.20.0: not found
```

**Environment**

* NTH App Version:
* NTH Mode (IMDS/Queue processor): 
* OS/Arch: amazon linux
* Kubernetes version: 1.28 (self managed via kops)
* Installation method: helm

**Comment by cjerad** [comment]
Hi @satra, as mentioned in issue #954 the release of v1.21.0 is not yet complete; progress updates will be posted there.

Regarding the error you received.  NTH and the helm chart are versioned independently.  `v1.20.0` is the NTH version which is installed by `v0.22.0` of the helm chart. You can view all versions of the helm chart published to Public ECR at https://gallery.ecr.aws/aws-ec2/helm/aws-node-termination-handler .

Using the helm chart's version should succeed:
```sh
$ helm upgrade --install aws-node-termination-handler --namespace kube-system oci://public.ecr.aws/aws-ec2/helm/aws-node-termination-handler --version 0.22.0
```

**Comment by satra** [comment]
@cjerad - let me try that again. i thought something errored when i did that.

**Comment by satra** [comment]
@cjerad - here is the feedback from running the helm upgrade command. this is on a fresh install of k8s 1.28. any advice would be much appreciated. 

cleaned by GPT:
Here's a more structured and detailed breakdown of the error message for clarity:

### Task: Add Termination Handler

- **Status**: FAILED
- **Target**: `ec2-18-224-190-104.us-east-2.compute.amazonaws.com`

### Command Execution:
- **Command**: `helm upgrade --install aws-node-termination-handler --namespace kube-system oci://public.ecr.aws/aws-ec2/helm/aws-node-termination-handler --version 0.22.0`
- **Duration**: 0:00:00.673737
- **Start Time**: 2024-02-09 18:33:40.528287
- **End Time**: 2024-02-09 18:33:41.202024
- **Result**: Error due to non-zero return code (rc: 1)

### Output Details:
- **Standard Output**:
  - "Release \"aws-node-termination-handler\" does not exist. Installing it now."

- **Error Output**:
  1. Pulled: `public.ecr.aws/aws-ec2/helm/aws-node-termination-handler:0.22.0`
  2. Digest: `sha256:31dfe02e549179f21c308c20f9be87ada93d0c39ae0277d3c564bf2a553f88f1`
  3. Error Message:
     - **Issue**: Unable to continue with install.
     - **Reason**: ServiceAccount "aws-node-termination-handler" in namespace "kube-system" exists and cannot be imported into the current release due to invalid ownership metadata.
       - **Label Validation Error**: The key `app.kubernetes.io/managed-by` must equal `Helm`. Current value: `kops`.
       - **Annotation Validation Errors**:
         - Missing key `meta.helm.sh/release-name`. Expected value: `aws-node-termination-handler`.
         - Missing key `meta.helm.sh/release-namespace`. Expected value: `kube-system`.

### Summary:
The Helm command failed to install or upgrade the AWS Node Termination Handler due to the presence of a ServiceAccount with conflicting ownership metadata. The ServiceAccount is managed by `kops` instead of `Helm`, and necessary annotations for Helm management are missing, leading to validation errors that prevented the operation from completing successfully.


original output:

```
TASK [Add termination handler] *********************************************************************************
fatal: [ec2-18-224-190-104.us-east-2.compute.amazonaws.com]: FAILED! => {"changed": true, "cmd": "helm upgrade --install aws-node-termination-handler --namespace kube-system oci://public.ecr.aws/aws-ec2/helm/aws-node-termination-handler --version 0.22.0", "delta": "0:00:00.673737", "end": "2024-02-09 18:33:41.202024", "msg": "non-zero return code", "rc": 1, "start": "2024-02-09 18:33:40.528287", "stderr": "Pulled: public.ecr.aws/aws-ec2/helm/aws-node-termination-handler:0.22.0\nDigest: sha256:31dfe02e549179f21c308c20f9be87ada93d0c39ae0277d3c564bf2a553f88f1\nError: Unable to continue with install: ServiceAccount \"aws-node-termination-handler\" in namespace \"kube-system\" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: key \"app.kubernetes.io/managed-by\" must equal \"Helm\": current value is \"kops\"; annotation validation error: missing key \"meta.helm.sh/release-name\": must be set to \"aws-node-termination-handler\"; annotation validation error: missing key \"meta.helm.sh/release-namespace\": must be set to \"kube-system\"", "stderr_lines": ["Pulled: public.ecr.aws/aws-ec2/helm/aws-node-termination-handler:0.22.0", "Digest: sha256:31dfe02e549179f21c308c20f9be87ada93d0c39ae0277d3c564bf2a553f88f1", "Error: Unable to continue with install: ServiceAccount \"aws-node-termination-handler\" in namespace \"kube-system\" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: key \"app.kubernetes.io/managed-by\" must equal \"Helm\": current value is \"kops\"; annotation validation error: missing key \"meta.helm.sh/release-name\": must be set to \"aws-node-termination-handler\"; annotation validation error: missing key \"meta.helm.sh/release-namespace\": must be set to \"kube-system\""], "stdout": "Release \"aws-node-termination-handler\" does not exist. Installing it now.", "stdout_lines": ["Release \"aws-node-termination-handler\" does not exist. Installing it now."]}
```

**Comment by satra** [comment]
looks like `kops` itself or some other component is adding a termination handler by default. hence some of the issues are probably related to that. will need to figure that out first.
