### ISSUE TITLE
Pod Identity Support and EKS 1.29

### ISSUE THREAD

**Issue by leolimas** [aws/aws-node-termination-handler#977]
I would like to confirm if version v1.21.0 already has support for Pod Identity and also when we will have official support for Kubernete 1.29?

**Comment by galtamirano-buk** [comment]
I'm also wondering if the current release supports eks 1.29... according to the matrix compatibility seems like not. Someone could clarify it ?

**Comment by mvink-guida** [comment]
> Hello, thanks for the questions.
> 
>     * NTH v1.21.0 does not use EKS Pod Identities
> 
>     * NTH v1.21.0, and older, have not yet been tested using k8s 1.29

ok and when will it get pod identity support?
