### ISSUE TITLE
Support for "safe-to-evict" annotation

### ISSUE THREAD

**Issue by Radoslaw-Kutylowski** [aws/aws-node-termination-handler#984]
**Describe the feature**
Kubernetes autoscalers use a "safe-to-evict" annotation (https://kubernetes.io/docs/reference/labels-annotations-taints/#cluster-autoscaler-kubernetes-io-safe-to-evict) to identify pods that should not be evicted while they are running. Would it be possible to add support for this, or a similar solution, in NTH? In many cases it would probably need a grace period after which a forceful drain would occur (e.g. in case of spot disruption).

**Is the feature request related to a problem?**
We have Kubernetes Jobs that are running tests. Sometimes these jobs are terminated e.g. by rebalance recommendations, that could wait a short while for the job to finish. This disrupts our CD workflows.

**Describe alternatives you've considered**
Outside of being open to other labels/annotations being used instead of the default "cluster-autoscaler" one, I do not have alternative ideas

**Comment by youwalther65** [comment]
Another use case I came across is long-running Kubernetes Jobs and ASG instance refresh. It would be great to wait for job to finish here.
