### ISSUE TITLE
question

### ISSUE THREAD

**Issue by dayyehm** [aws/aws-node-termination-handler#99]
The documentation states it will cordon the node and drain it.  Does it do that on its' own and how does that play with the existing auto scaling group and the lifecycle hooks we have configured for drains?  We watch to make sure certain daemonsets/deploy/pods have been terminated before continuing etc.

**Comment by bwagner5** [comment]
aws-node-termination-handler runs as a daemonset on all nodes and will automatically cordon the node and drain the pods off the node when it gets a Spot ITN or scheduled maintenance event. This should not interfere with your ASG lifecycle hooks except that the nodes will most likely already be drained from the aws-node-termination-handler.

**Comment by dayyehm** [comment]
Thank you
